entities:
  jd_b2b_order_dtl:
    edw_prefix: f
    stg_suffix: di
    key: id
    update_type: F
    dm_dependicies: jd_b2b_order,jd_pop_order_dtl,dl_jd_order,dl_jd_order_dtl,dl_dly_sales_rpt,dl_jd_shopper,jd_member

  jd_member:
    edw_prefix: d_dl
    stg_suffix: di
    key: member_id
    update_type: SCD2
    dm_dependicies: jd_b2b_order_dtl,jd_b2b_order,jd_pop_order_dtl,jd_pop_order,dl_jd_order,dl_jd_order_dtl,dl_dly_sales_rpt,dl_jd_shopper

  jd_pop_order:
    edw_prefix: f
    stg_suffix: di
    key: id
    update_type: F
    dm_dependicies: jd_pop_order_dtl,jd_member,jd_b2b_order,jd_b2b_order_dtl,dl_jd_order,dl_jd_order_dtl,dl_dly_sales_rpt,dl_jd_shopper

  jd_pop_order_dtl:
    edw_prefix: f
    stg_suffix: di
    key: id
    update_type: F
    dm_dependicies: jd_pop_order,dl_jd_order,dl_jd_order_dtl,dl_dly_sales_rpt,dl_jd_shopper

  jd_pop_consignee:
    edw_prefix: f
    stg_suffix: di
    key: id
    update_type: SCD2
    dm_dependicies: jd_pop_order
    dm_sync: False
    encrypted_columns: telephone,mobile
    to_encrypt_columns: telephone,mobile

  bu_jd_pop_sku_map:
    edw_prefix: d
    stg_suffix: di
    key: store_sku_id
    update_type: F
    dm_sync: False
    dm_dependicies: jd_pop_order_dtl,jd_pop_order,dl_jd_order,dl_jd_order_dtl,dl_dly_sales_rpt,dl_jd_shopper


  bu_jd_b2b_sku_map:
    edw_prefix: d
    stg_suffix: di
    key: store_sku_id
    update_type: F
    dm_sync: False
    dm_dependicies: jd_b2b_order_dtl,jd_b2b_order,dl_jd_order,dl_jd_order_dtl,dl_dly_sales_rpt,dl_jd_shopper

  bu_tm_sku_map:
    edw_prefix: d
    stg_suffix: di
    key: store_sku_id
    update_type: F
    dm_sync: False
    dm_dependicies: dl_product_info,oms_order_dtl,dl_dly_sales_rpt,dl_tm_shopper

  bu_mly_jd_traffic:
    edw_prefix: a
    stg_suffix: di
    key: store,yearmonth
    update_type: F

  bu_mly_tm_traffic:
    edw_prefix: a
    stg_suffix: di
    key: store,yearmonth
    update_type: F

  bu_dly_jd_traffic:
    edw_prefix: a
    stg_suffix: di
    key: store,date
    update_type: F
    dm_dependicies: dl_dly_sales_rpt

  bu_dly_tm_traffic:
    edw_prefix: a
    stg_suffix: di
    key: store,date
    update_type: F
    dm_dependicies: dl_dly_sales_rpt

  # dl_product_info:
  #   edw_prefix: d
  #   stg_suffix: df
  #   key: material_id,year_version
  #   update_type: F
  #   dm_dependicies: jd_b2b_order_dtl,jd_b2b_order,jd_pop_order_dtl,jd_pop_order,dl_jd_order,dl_jd_order_dtl,dl_dly_sales_rpt,oms_order_dtl,dl_jd_shopper,dl_tm_shopper

  dl_product_info_v2:
    edw_prefix: d
    stg_suffix: df
    key: material_id,year_version
    update_type: F
    column_positions: '{"prodcut_info":{"filename":"\\d{4}\\sMG China Assortment.*","all_reg":"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,/,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53
"}}'

  bu_tm_gwp:
    edw_prefix: d
    stg_suffix: df
    key: store_sku_id
    update_type: F
    dm_sync: False
    dm_dependicies: oms_order_dtl,dl_dly_sales_rpt,dl_tm_shopper

  bu_jd_b2b_gwp:
    edw_prefix: d
    stg_suffix: df
    key: store_sku_id
    update_type: F
    dm_dependicies: jd_b2b_order_dtl,jd_b2b_order,dl_jd_order,dl_jd_order_dtl,dl_dly_sales_rpt,dl_jd_shopper
    dm_sync: False

  bu_jd_pop_gwp:
    edw_prefix: d
    stg_suffix: df
    key: store_sku_id
    update_type: F
    dm_dependicies: jd_pop_order_dtl,jd_pop_order,dl_jd_order,dl_jd_order_dtl,dl_dly_sales_rpt,dl_jd_shopper
    dm_sync: False

  dl_calendar:
    edw_prefix: d
    stg_suffix: yf
    key: id
    update_type: F

  dl_city_tier:
    edw_prefix: d
    stg_suffix: yf
    key: city_chn,year
    update_type: F

  wc_mini_member_info:
    edw_prefix: f
    stg_suffix: yf
    key: unionid
    update_type: F
    encrypted_columns: mobile,unionid,openid
    to_encrypt_columns: mobile

  cs_consumer_info:
    edw_prefix: f
    stg_suffix: di
    key: partner
    update_type: F

  jd_pop_order_dtl_his:
    edw_prefix: f
    stg_suffix: mi
    key: parent_order_id,store_sku_id
    update_type: F
    to_encrypt_columns: cosignee_contact,taxpayer_phone

  jd_order_his:
    edw_prefix: f
    stg_suffix: mi
    key: parent_order_id,shopper_nickname
    update_type: F

  jd_order_dtl_his:
    edw_prefix: f
    stg_suffix: mi
    key: parent_order_id,store_sku_id
    update_type: F

  jd_b2b_order_dtl_his:
    edw_prefix: f
    stg_suffix: mi
    key: parent_order_id,store_sku_id
    update_type: F

  oms_order:
    edw_prefix: f
    stg_suffix: di
    key: id
    update_type: F
    dm_dependicies: dl_dly_sales_rpt,oms_order_dtl,dl_tm_shopper


  oms_order_dtl:
    edw_prefix: f
    stg_suffix: di
    key: id
    update_type: F
    dm_dependicies: dl_dly_sales_rpt,oms_order,dl_tm_shopper

  oms_return_order:
    edw_prefix: f
    stg_suffix: di
    key: id
    update_type: F

  oms_return_order_dtl:
    edw_prefix: f
    stg_suffix: di
    key: id
    update_type: F

  tm_order_dtl_his:
    edw_prefix: f
    stg_suffix: mi
    key: parent_order_id,external_sku_id
    update_type: F

  tm_order_his:
    edw_prefix: f
    stg_suffix: mi
    key: parent_order_id
    update_type: F
    to_encrypt_columns: consinee_mobile,consinee_telephone

  tm_order_dtl_2018_his:
    edw_prefix: f
    stg_suffix: mi
    key: parent_order_id,son_order_id
    update_type: F

  dl_scv:
    key: consumer_id
    update_type: F

  dl_mly_sales_rpt:
    key: yearmonth,kpi_name,store
    dm_dependicies: dl_mly_sales_rpt

  tm_member_his:
    edw_prefix: d_dl
    update_type: SCD2-MD5
    stg_suffix: mi
    key: shopperid
    to_encrypt_columns: mobile

  tm_member_1st_purchase_his:
    edw_prefix: d_dl
    update_type: F
    stg_suffix: mi
    key: shopperid
    to_encrypt_columns: mobile

  tm_member:
    edw_prefix: d
    update_type: F
    key: shopperid
    dm_dependicies: dl_dly_sales_rpt,oms_order_dtl
    dm_sync: False

  qbt_sku_monitor:
    edw_prefix: f
    update_type: SCD3
    stg_suffix: mi
    key: year,month,week,start_time,end_time,brand,lego_sku_id,sku_cn_name,platform,shop
    dm_sync: False

  qbt_store_sales:
    edw_prefix: f
    update_type: F
    stg_suffix: mi
    key: platform,year,month,shop,shopkeeper_name
    dm_sync: False

  qbt_brand_sales:
    edw_prefix: f
    update_type: F
    stg_suffix: mi
    key:  year,month,platform,primary_category,brand
    dm_sync: False

  qbt_tmall_global:
    edw_prefix: f
    update_type: F
    stg_suffix: mi
    key: year,month,shop,store_sku_name,category,link
    dm_sync: False

  qbt_toy_industry_sales:
    edw_prefix: f
    update_type: F
    stg_suffix: mi
    key: platform,year,month,primary_category,second_category
    dm_sync: False

  qbt_building_toy_industry_sales:
    edw_prefix: f
    update_type: F
    stg_suffix: mi
    key: platform,year,month,primary_category,second_category,third_category
    dm_sync: False

  phy_store_order:
    edw_prefix: f
    update_type: F
    stg_suffix: di
    key: distributor,distributor_store_code,parent_order_id
    dm_sync: False

  phy_store_order_dtl:
    edw_prefix: f
    update_type: F
    stg_suffix: di
    key: distributor,distributor_store_code,parent_order_id,lego_sku_id,lego_sku_asp_price
    dm_sync: False

  phy_store_order_payment_dtl:
    edw_prefix: f
    update_type: F
    stg_suffix: di
    key: distributor,distributor_store_code,parent_order_id,payment_type
    dm_sync: False

  phy_store_order_coupon_dtl:
    edw_prefix: f
    update_type: F
    stg_suffix: di
    key: distributor,distributor_store_code,parent_order_id,coupon_code
    dm_sync: False

  phy_store_return_order:
    edw_prefix: f
    update_type: F
    stg_suffix: di
    key: distributor,distributor_store_code,return_order_id
    dm_sync: False

  phy_store_return_order_dtl:
    edw_prefix: f
    update_type: F
    stg_suffix: di
    key: distributor,return_order_id,lego_sku_id
    dm_sync: False

  phy_store:
    edw_prefix: f
    update_type: F
    stg_suffix: di
    key: distributor,lego_store_code
    dm_sync: False

  phy_store_handwork:
    edw_prefix: f
    update_type: SCD2
    stg_suffix: di
    key: distributor,lego_store_code
    dm_sync: False

  phy_store_warehouse_inventory:
    edw_prefix: f
    update_type: F
    stg_suffix: di
    key: distributor,stats_time,lego_sku_id
    dm_sync: False

  phy_store_inventory:
    edw_prefix: f
    update_type: F
    stg_suffix: di
    key: distributor,distributor_store_code,lego_store_code,stats_time,lego_sku_id
    dm_sync: False

  phy_store_traffic:
    edw_prefix: f
    update_type: F
    stg_suffix: di
    key: distributor,distributor_store_code,lego_store_code,stats_time
    dm_sync: False

  phy_store_member:
    edw_prefix: f
    update_type: SCD2
    stg_suffix: di
    key: distributor,member_id
    dm_sync: False

  phy_store_member_point:
    edw_prefix: f
    update_type: F
    stg_suffix: di
    key: distributor,member_id,stats_time
    dm_sync: False

  phy_store_point_transaction:
    edw_prefix: f
    update_type: F
    stg_suffix: di
    key: distributor,member_id,trans_id
    dm_sync: False

  phy_store_coupon:
    edw_prefix: f
    update_type: F
    stg_suffix: di
    key: distributor,coupon_code
    dm_sync: False

  oms_income_expense:
    edw_prefix: f
    update_type: F
    stg_suffix: di
    key: id,flag
    dm_dependicies: oms_promotion_info

  oms_income_statement:
    edw_prefix: f
    update_type: F
    stg_suffix: di
    key: id,flag

  oms_expense_statement:
    edw_prefix: f
    update_type: F
    stg_suffix: di
    key: id,flag

  dl_mini_member_distribution:
    edw_prefix: f
    update_type: SCD3
    stg_suffix: di
    key: unionid

  lgc_sales_stock_nip_dkk:
    edw_prefix: f
    update_type: f
    stg_suffix: di
    productcode_index: "6"
    column_positions: '{"sales_stock_nip_dkk":{"filename":"sales_stock_nip_dkk.*","all_reg":"0,1,2,3,4,5,6,7,8,9,10,11"}}'
    key: year_week,cust_id,store_id,prod_id

  lgc_sales_stock_rrp_rmb:
    edw_prefix: f
    update_type: f
    stg_suffix: di
    productcode_index: "6"
    column_positions: '{"sales_stock_rrp_rmb":{"filename":"sales_stock_rrp_rmb.*","all_reg":"0,1,2,3,4,5,6,7,8,9,10,11"}}'
    key: year_week,cust_id,store_id,prod_id

  lgc_customer_name_mapping:
    edw_prefix: f
    update_type: f
    stg_suffix: di
    column_positions:  '{"lgc_customer_name_mapping":{"filename":"lgc_customer_name_mapping.*","all_reg":"0,1"}}'
    key: customer,correct_customer

  lgc_store_closure_list:
    edw_prefix: f
    update_type: f
    stg_suffix: di
    column_positions:  '{"lgc_store_closure_list":{"filename":"lgc_store_closure_list.*","all_reg":"0,1,2,3"}}'
    key: store,close_date

  lgc_store_renovation_record:
    edw_prefix: f
    update_type: f
    stg_suffix: di
    column_positions: '{"lgc_store_renovation_record":{"filename":"lgc_store_renovation.*","all_reg":"0,1,2,3,4"}}'
    key: store,close_date

  lgc_instock:
    edw_prefix: f
    update_type: f
    stg_suffix: di
    productcode_index: "5"
    column_positions: '{"instock":{"filename":"instock.*","all_reg":"0,1,2,3,4,5,6,7,8,9,10,11,12,13"}}'
    key: year_week,cust_id,store_id,prod_id

  lgc_sellin:
    edw_prefix: f
    update_type: f
    stg_suffix: di
    productcode_index: "5"
    column_positions: '{"sellin":{"filename":"sellin.*","all_reg":"0,1,2,3,4,5,6,7,8,9,10,11,12,13"}}'
    key: date,cust_link,prod_id

  lgc_plan_nip_dkk:
    edw_prefix: f
    update_type: f
    stg_suffix: di
    column_positions: '{"plan_nip_dkk":{"filename":"plan_nip_dkk.*","all_reg":"0,-,1,2,3,4,5,6,7,8,9,10,11,12,13,-"}}'
    key: year,customer,plan_vision

  lgc_plan_rrp_rmb:
    edw_prefix: f
    update_type: f
    stg_suffix: di
    column_positions: '{"plan_rrp_rmb":{"filename":"plan_rrp_rmb.*","sheets":"0,-,1,2,3,4,5,6,7,8,9,10,11,12,13,-"}}'
    key: year,customer,plan_vision

  lgc_plan_nip_dkk_portfolio:
    edw_prefix: f
    update_type: f
    stg_suffix: di
    column_positions: '{"plan_nip_dkk_portfolio":{"filename":"plan_nip_dkk_portfolio.*","all_reg":"0,-,1,2,3,4,5,6,7,8,9,10,11,12,13,14,-"}}'
    key: year,customer,plan_vision

  lgc_plan_rrp_rmb_portfolio:
    edw_prefix: f
    update_type: f
    stg_suffix: di
    column_positions: '{"plan_rrp_rmb_portfolio":{"filename":"plan_rrp_rmb_portfolio.*","all_reg":"0,-,1,2,3,4,5,6,7,8,9,10,11,12,13,14,-"}}'
    key: year,customer,plan_vision

  lgc_cs_weekly_phasing:
    edw_prefix: f
    update_type: f
    stg_suffix: di
    column_positions: '{"cs_weekly_phasing":{"filename":"cs_weekly_phasing.*","all_reg":"0,1,2,3,4,5,6,7,8,9,10,11,12"}}'
    key: customer,month

  lgc_lcs_store_bd:
    edw_prefix: f
    update_type: f
    stg_suffix: di
    column_positions: '{"lgc_lcs_store_bd":{"filename":"lgc_lcs_store_bd.*","all_reg":"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77"}}'
    key: store_code,year,opening_month

  lgc_modified_product:
    edw_prefix: f
    update_type: f
    stg_suffix: di
    column_positions: '{"lgc_modified_product":{"filename":"lgc_modified_product.*","all_reg":"0,1,2,3"}}'
    key: channel,temp_product

  lgc_product_infor:
    edw_prefix: f
    update_type: f
    stg_suffix: di
    column_positions: '{"prodcut_infor":{"filename":"*.list_product.*","all_reg":"-,0,1,2,3,4,5,6,7,8,9,11,12,13,14,15,16,17,19,18,23,27,20,21,-,24,25,-,26,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,-
"}}'
    key: year_version,lego_sku_id

  lgc_phy_store:
    edw_prefix: f
    update_type: f
    stg_suffix: di
    column_positions: '{"phy_store":[
    {"filename":"StoreList_B2B2F.*","all_reg":"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19"}, 
    {"filename":"StoreList_Collaboration.*","all_reg":"0,1,2,5,4,6,7,8,9,10,3,11,12,13,14,15,16,17,18,19"},
    {"filename":"StoreList_EMP.*","all_reg":"0,1,2,5,3,11,6,13,8,7,9,12,4,14,15,16,10,17,18,19"},
    {"filename":"StoreList_Kidsland.*","all_reg":"1,2,3,5,13,0,6,15,9,8,4,14,7,10,11,12,16,18,19"},
    {"filename":"StoreList_Kidswant.*","all_reg":"1,2,0,4,3,12,5,10,8,7,9,11,6,13,14,15,16,18,19"},
    {"filename":"StoreList_LDC.*","all_reg":"3,4,5,6,2,1,7,12,9,10,0,11,8,13,14,15,16,17,18,19"},
    {"filename":"StoreList_TRU.*","all_reg":"2,3,4,7,5,1,8,9,11,10,0,12,6,13,14,15,16,17,18,19"},
    {"filename":"StoreList_LCS.*","all_reg":"2,3,4,7,5,1,8,9,11,10,0,12,6,13,14,15,16,17,18,19"}]}'
    key: store_code


  lgc_plan_lbr_net_dkk_portfolio:
    edw_prefix: f
    update_type: f
    stg_suffix: di
    column_positions: '{"plan_lbr_net_dkk_portfolio":{"filename":"plan_lbr_net_dkk_portfolio.*","all_reg":"0,1,2,3,4,5,6"}}'
    key: channel_code,calendar_year,cs_plan_version,cs_plan_month,top_theme

  lgc_sales_stock_pos:
    edw_prefix: f
    update_type: f
    stg_suffix: di
    productcode_index: "3"
    column_positions: '{"DLH":{"filename":"DLH.*","all_reg":"0,1,2,3,5,4,-"}}'
    key: date,storecode,transactioncode,productcode

  dl_phy_store:
    edw_prefix: d
    stg_suffix: df
    key: distributor,lego_store_code
    update_type: F