name: dev CD/CD deployment

on:
  push:
    branches:
      - dev
jobs:
  test-deploy:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: test deploy to airflow 
      run: cp -rf ./dags/ /home/github_runner/test/