Staging:
  src_columns:
    id text,
    date_id text,
    date_type text,
    d_day text,
    d_week text,
    d_month text,
    d_quarter text,
    d_year text,
    fiscal_year text,
    is_chinese_holiday text,
    is_holiday text,
    start_time text,
    end_time text,
    lego_day text,
    lego_week text,
    lego_week_code text,
    lego_week_name text,
    lego_month text,
    lego_month_disp text,
    lego_quarter text,
    lego_year text,
    lego_start_time text,
    lego_end_time text
ODS:

EDW:
  create_table_query:
    CREATE TABLE if not exists edw.d_dl_calendar(
    id varchar(30),
    date_id date NULL,
    date_type varchar(10),
    d_day int NULL,
    d_week int NULL,
    d_month int NULL,
    d_quarter int null,
    d_year int NULL,
    fiscal_year int NULL,
    is_chinese_holiday varchar(1) NULL,
    is_holiday varchar(1) NULL,
    start_time timestamp NULL,
    end_time timestamp NULL,
    lego_day varchar(10) NULL,
    lego_week int NULL,
    lego_week_code varchar(10) NULL,
    lego_week_name varchar(10) NULL,
    lego_month int NULL,
    lego_month_disp varchar(10)  null,
    lego_quarter varchar(10) null,
    lego_year int NULL,
    lego_start_time TIMESTAMP NULL,
    lego_end_time TIMESTAMP NULL,
    dl_batch_date varchar(8),
    dl_load_time timestamp,
    constraint pk_calendar_id primary key( id)
    )distributed by (id)
  
  insert_edw_from_ods_query:
    insert into edw.d_dl_calendar(
    id,
    date_id,
    date_type,
    d_day,
    d_week,
    d_month,
    d_quarter,
    d_year,
    fiscal_year,
    is_chinese_holiday,
    is_holiday,
    start_time,
    end_time,
    lego_day,
    lego_week,
    lego_week_code,
    lego_week_name,
    lego_month,
    lego_month_disp,
    lego_quarter,
    lego_year,
    lego_start_time,
    lego_end_time,
    dl_batch_date,
    dl_load_time
    )
    select
    id,
    to_date(date_id,'YYYY-MM-DD'),
    date_type,
    d_day::int,
    d_week::int,
    d_month::int,
    d_quarter::int,
    d_year::int,
    fiscal_year::int,
    is_chinese_holiday,
    is_holiday,
    to_timestamp(start_time,'YYYY-MM-DD HH24:MI:SS'),
    to_timestamp(end_time,'YYYY-MM-DD HH24:MI:SS'), 
    lego_day,
    lego_week::int,
    lego_week_code,
    lego_week_name,
    lego_month::int,
    lego_month_disp,
    lego_quarter::int,
    lego_year::int,
    to_timestamp(lego_start_time,'YYYY-MM-DD HH24:MI:SS'),
    to_timestamp(lego_end_time,'YYYY-MM-DD HH24:MI:SS'),
    dl_batch_date,
    now()
    from ods.r_dl_calendar;

  sync_to_rds_dm:
    create table if not exists dm.d_dl_calendar (like frn.d_dl_calendar);

    delete from dm.d_dl_calendar;
    delete from dm.d_dl_calendar;
    
    insert into dm.d_dl_calendar  select *   from frn.d_dl_calendar;
    

