Staging:
  src_columns:
    customer text,
    month text,
    first_week text,
    second_week text,
    third_week text,
    fourth_week text,
    fifth_week text,
    total text,
    first_week_percent text,
    second_week_percent text,
    third_week_percent text,
    fourth_week_percent text,
    fifth_week_percent text

ODS:

EDW:
  create_edw_table_query:
    create table if not exists edw.f_lgc_cs_weekly_phasing(
       c6_linking_distributor_name     varchar(200),
       distributor_name         varchar(200),
       plan_lego_year_month     varchar(10),
       xth_week                 bigint,
       plan_value               numeric(17,2),
       dl_batch_date            varchar(200),
       dl_load_time             timestamp,
       constraint pk_f_lgc_cs_weekly_phasing primary key(c6_linking_distributor_name,plan_lego_year_month)
    )distributed by (plan_lego_year_month);

  insert_edw_table_query:
    delete from edw.f_lgc_cs_weekly_phasing;
    insert into edw.f_lgc_cs_weekly_phasing
    select
       customer           as c6_linking_distributor_name,
       replace(customer,'6 CN ','')          as distributor_name,
       month             as plan_lego_year_month,
       1                 as xth_week,
       cast(first_week as numeric(17,2))as plan_value,
       dl_batch_date     as dl_batch_date,
       now()             as dl_load_time
    from
        ods.r_lgc_cs_weekly_phasing
    where first_week is not null
    union all
    select
       customer           as c6_linking_distributor_name,
       replace(customer,'6 CN ','')          as distributor_name,
       month             as plan_lego_year_month,
       2                 as xth_week,
       cast(second_week as numeric(17,2))as plan_value,
       dl_batch_date     as dl_batch_date,
       now()             as dl_load_time
    from
        ods.r_lgc_cs_weekly_phasing
    where second_week is not null
    union all
    select
       customer              as c6_linking_distributor_name,
       replace(customer,'6 CN ','')          as distributor_name,
       month             as plan_lego_year_month,
       3                 as xth_week,
       cast(third_week as numeric(17,2))as plan_value,
       dl_batch_date     as dl_batch_date,
       now()             as dl_load_time
    from
        ods.r_lgc_cs_weekly_phasing
    where third_week is not null
    union all
    select
       customer              as c6_linking_distributor_name,
       replace(customer,'6 CN ','')          as distributor_name,
       month             as plan_lego_year_month,
       4                 as xth_week,
       cast(fourth_week as numeric(17,2))as plan_value,
       dl_batch_date     as dl_batch_date,
       now()             as dl_load_time
    from
        ods.r_lgc_cs_weekly_phasing
    where fourth_week is not null
    union all
    select
       customer              as c6_linking_distributor_name,
       replace(customer,'6 CN ','')          as distributor_name,
       month             as plan_lego_year_month,
       5                 as xth_week,
       cast(fifth_week as numeric(17,2))as plan_value,
       dl_batch_date     as dl_batch_date,
       now()             as dl_load_time
    from
        ods.r_lgc_cs_weekly_phasing
    where fifth_week is not null    ;
