Staging:
  src_columns:
    channel text,
    cnline text,
    year text,
    jan text,
    feb text,
    mar text,
    apr text,
    may text,
    jun text,
    jul text,
    aug text,
    sep text,
    oct text,
    nov text,
    dec text,
    plan_version text

ODS:

EDW:
  create_edw_table_query:
    create table if not exists edw.f_lgc_plan_rrp_rmb_portfolio(
       channel_name         varchar(200),
       top_theme            varchar(200),
       plan_lego_year       varchar(10),
       plan_lego_month      varchar(4),
       plan_version         varchar(200),
       plan_amt             numeric(17,2),
       data_version         varchar(200),
       dl_batch_date        varchar(200),
       dl_load_time         timestamp,
       constraint pk_f_lgc_plan_rrp_rmb_portfolio primary key(channel_name,top_theme,plan_lego_year,plan_lego_month,plan_version)
    )distributed by (plan_lego_year);

  insert_edw_table_query:
    delete from edw.f_lgc_plan_rrp_rmb_portfolio;
    insert into edw.f_lgc_plan_rrp_rmb_portfolio
    select
        channel                     as channel_name,
        cnline                      as top_theme,
        year                        as plan_lego_year,
        '01'                        as plan_lego_month,
        plan_version                as plan_version,
        cast(jan as numeric(17,2))  as plan_amt,
        'RRP RMB'                   as data_version,
        dl_batch_date               as dl_batch_date,
        now()                       as dl_load_time
    from
        ods.r_lgc_plan_rrp_rmb_portfolio
    where jan is not null
    union all
    select
        channel                     as channel_name,
        cnline                      as top_theme,
        year                        as plan_lego_year,
        '02'                        as plan_lego_month,
        plan_version                as plan_version,
        cast(feb as numeric(17,2))  as plan_amt,
        'RRP RMB'                   as data_version,
        dl_batch_date               as dl_batch_date,
        now()                       as dl_load_time
    from
        ods.r_lgc_plan_rrp_rmb_portfolio
    where feb is not null
    union all
    select
        channel                     as channel_name,
        cnline                      as top_theme,
        year                        as plan_lego_year,
        '03'                        as plan_lego_month,
        plan_version                as plan_version,
        cast(mar as numeric(17,2))  as plan_amt,
        'RRP RMB'                   as data_version,
        dl_batch_date               as dl_batch_date,
        now()                       as dl_load_time
    from
        ods.r_lgc_plan_rrp_rmb_portfolio
    where mar is not null
    union all
    select
        channel                     as channel_name,
        cnline                      as top_theme,
        year                        as plan_lego_year,
        '04'                        as plan_lego_month,
        plan_version                as plan_version,
        cast(apr as numeric(17,2))  as plan_amt,
        'RRP RMB'                   as data_version,
        dl_batch_date               as dl_batch_date,
        now()                       as dl_load_time
    from
        ods.r_lgc_plan_rrp_rmb_portfolio
    where apr is not null
    union all
    select
        channel                     as channel_name,
        cnline                      as top_theme,
        year                        as plan_lego_year,
        '05'                        as plan_lego_month,
        plan_version                as plan_version,
        cast(may as numeric(17,2))  as plan_amt,
        'RRP RMB'                   as data_version,
        dl_batch_date               as dl_batch_date,
        now()                       as dl_load_time
    from
        ods.r_lgc_plan_rrp_rmb_portfolio
    where may is not null
    union all
    select
        channel                     as channel_name,
        cnline                      as top_theme,
        year                        as plan_lego_year,
        '06'                        as plan_lego_month,
        plan_version                as plan_version,
        cast(jun as numeric(17,2))  as plan_amt,
        'RRP RMB'                   as data_version,
        dl_batch_date               as dl_batch_date,
        now()                       as dl_load_time
    from
        ods.r_lgc_plan_rrp_rmb_portfolio
    where jun is not null
    union all
    select
        channel                     as channel_name,
        cnline                      as top_theme,
        year                        as plan_lego_year,
        '07'                        as plan_lego_month,
        plan_version                as plan_version,
        cast(jul as numeric(17,2))  as plan_amt,
        'RRP RMB'                   as data_version,
        dl_batch_date               as dl_batch_date,
        now()                       as dl_load_time
    from
        ods.r_lgc_plan_rrp_rmb_portfolio
    where jul is not null
    union all
    select
        channel                     as channel_name,
        cnline                      as top_theme,
        year                        as plan_lego_year,
        '08'                        as plan_lego_month,
        plan_version                as plan_version,
        cast(aug as numeric(17,2))  as plan_amt,
        'RRP RMB'                   as data_version,
        dl_batch_date               as dl_batch_date,
        now()                       as dl_load_time
    from
        ods.r_lgc_plan_rrp_rmb_portfolio
    where aug is not null
    union all
    select
        channel                     as channel_name,
        cnline                      as top_theme,
        year                        as plan_lego_year,
        '09'                        as plan_lego_month,
        plan_version                as plan_version,
        cast(sep as numeric(17,2))  as plan_amt,
        'RRP RMB'                   as data_version,
        dl_batch_date               as dl_batch_date,
        now()                       as dl_load_time
    from
        ods.r_lgc_plan_rrp_rmb_portfolio
    where sep is not null
    union all
    select
        channel                     as channel_name,
        cnline                      as top_theme,
        year                        as plan_lego_year,
        '10'                        as plan_lego_month,
        plan_version                as plan_version,
        cast(oct as numeric(17,2))  as plan_amt,
        'RRP RMB'                   as data_version,
        dl_batch_date               as dl_batch_date,
        now()                       as dl_load_time
    from
        ods.r_lgc_plan_rrp_rmb_portfolio
    where oct is not null
    union all
    select
        channel                     as channel_name,
        cnline                      as top_theme,
        year                        as plan_lego_year,
        '11'                        as plan_lego_month,
        plan_version                as plan_version,
        cast(nov as numeric(17,2))  as plan_amt,
        'RRP RMB'                   as data_version,
        dl_batch_date               as dl_batch_date,
        now()                       as dl_load_time
    from
        ods.r_lgc_plan_rrp_rmb_portfolio
    where nov is not null
    union all
    select
        channel                     as channel_name,
        cnline                      as top_theme,
        year                        as plan_lego_year,
        '12'                        as plan_lego_month,
        plan_version                as plan_version,
        cast(dec as numeric(17,2))  as plan_amt,
        'RRP RMB'                   as data_version,
        dl_batch_date               as dl_batch_date,
        now()                       as dl_load_time
    from
        ods.r_lgc_plan_rrp_rmb_portfolio
    where dec is not null;