Staging:
  src_columns:
    store text,
    close_date text,
    reopen_date text,
    floor text,
    sales_space text

ODS:

EDW:
  create_edw_table_query:
    create table if not exists edw.f_lgc_store_revn_list(
    date_id varchar(20),
    lego_store_code varchar(100),
    close_date varchar(20),
    reopen_date varchar(20),
    store_floor varchar(100),
    sales_space numeric(17,2),
    dl_batch_date varchar(20),
    dl_load_time timestamp,
    constraint pk_f_lgc_store_revn_list primary key(lego_store_code, close_date)
    )distributed by (lego_store_code);

  delete_edw_table_query:
    delete from edw.f_lgc_store_revn_list;

  insert_edw_table_query:
    insert into edw.f_lgc_store_revn_list
    select 
        to_char(to_date(close_date, 'dd/mm/yyyy'),'yyyymmdd')  as date_id,
        store              as lego_store_code,
        to_char(to_date(close_date, 'dd/mm/yyyy'),'yyyymmdd')  as close_date,
        to_char(to_date(reopen_date, 'dd/mm/yyyy'),'yyyymmdd') as reopen_date,
        floor              as store_floor,
        sales_space        as sales_space,
        dl_batch_date      as dl_batch_date,
        now()              as dl_load_time
    from 
       ods.r_lgc_store_renovation_record;