Staging:
  src_columns:
    year_version text,
    lego_sku_id text,
    material_id text,
    version text,
    lego_sku_name_en text,
    lego_sku_name_cn text,
    RSP text,
    global_launch_date text,
    global_delete_date text,
    embargo_date text,
    is_bu_d2c_launch text,
    bu_d2c_launch_date text,
    bu_d2c_delete_date text,
    is_bu_cn_launch text,
    bu_cn_launch_date text,
    cn_lcs_launch_date text,
    cn_ldc_launch_date text,
    cn_tm_launch_date text,
    cn_jd_b2b_launch_date text,
    cn_jd_pop_launch_date text,
    cn_tru_launch_date text,
    cn_b2b2f_launch_date text,
    cn_dsp_launch_date text,
    cn_dls_ds_launch_date text,
    cn_hamleys_launch_date text,
    cn_kl_Indirect_launch_date text,
    cn_kidsland_online_b2c_launch_date text,
    cn_wc_mini_Program_launch_date text,
    cn_kidswant_launch_date text,
    exclusive_products text,
    bu_cn_delete_date text,
    product_status text,
    in_and_out text,
    super_segment text,
    prod_cat text,
    product_bu text,
    theme text,
    product_group text,
    cn_line text,
    top_theme text,
    product_class text,
    material_group text,
    is_batteries_included text,
    age_mark text,
    piece_count text,
    case_pack text,
    lbs_size text,
    net_weight_kg text,
    length_mm text,
    width_mm text,
    height_mm text,
    product_ean_code text,
    carton_ean_code text,
    new_List_price_pricelist_ab_china text,
    new_ldc_extended_line_list_pricetext text
ODS:

EDW:
  create_table_query:
    
  
  insert_edw_from_ods_query:



