Staging:
  src_columns:
    year_week text,
    cust_link text,
    cust_name text,
    cust_id text,
    cust_loca text,
    store_id text,
    prod_id text,
    prod_name text,
    cst_cnsmr_sale_rrp text,
    cst_cnsmr_sale_qty text,
    cst_retail_stock_qty text,
    cst_retail_stock_rrp text
    
ODS:

EDW:
  create_table_query:
  insert_edw_from_ods_query:
