Staging:
  src_columns:
    channel text,
    cnline text,
    year text,
    jan text,
    feb text,
    mar text,
    apr text,
    may text,
    jun text,
    jul text,
    aug text,
    sep text,
    oct text,
    nov text,
    dec text,
    plan_version text

ODS:

EDW:
  create_edw_table_query:
    create table if not exists edw.f_lgc_plan_nip_dkk_portflio(
       date_id       varchar(20),
       channel       varchar(20),
       prod_line     varchar(100),
       year          varchar(10),
       month         varchar(10),
       plan_version  varchar(20),
       plan_value    numeric(17,2),
       dl_batch_date varchar(10),
       dl_load_time  timestamp,
       constraint pk_f_lgc_plan_nip_dkk_portflio primary key(channel,prod_line,year,month,plan_version)
    )distributed by (year);

  delete_edw_table_query:
     delete from edw.f_lgc_plan_nip_dkk_portflio;

  insert_edw_table_query:
    insert into edw.f_lgc_plan_nip_dkk_portflio
    select
         (case when year is null then'2021' else year end)||'14'||'01' as date_id,
        channel                     as channel,
        cnline                      as prod_line,
         (case when year is null then'2021' else year end) as year,
        '01'                        as month,
        plan_version                as plan_version,
        cast(jan as numeric(17,2))  as plan_value,
        dl_batch_date               as dl_batch_date,
        now()                       as dl_load_time
    from
        ods.r_lgc_plan_nip_dkk_portfolio
    where jan is not null
    union all
    select
         (case when year is null then'2021' else year end)||'14'||'02' as date_id,
        channel                     as channel,
        cnline                    as prod_line,
         (case when year is null then'2021' else year end) as year,
        '02'                        as month,
        plan_version                as plan_version,
        cast(feb as numeric(17,2))  as plan_value,
        dl_batch_date               as dl_batch_date,
        now()                       as dl_load_time
    from
        ods.r_lgc_plan_nip_dkk_portfolio
    where feb is not null
    union all
    select
         (case when year is null then'2021' else year end)||'14'||'03'  as date_id,
        channel                     as channel,
        cnline                    as prod_line,
         (case when year is null then'2021' else year end)  as year,
        '03'                        as month,
        plan_version                as plan_version,
        cast(mar as numeric(17,2))  as plan_value,
        dl_batch_date               as dl_batch_date,
        now()                       as dl_load_time
    from
        ods.r_lgc_plan_nip_dkk_portfolio
    where mar is not null
    union all
    select
         (case when year is null then'2021' else year end)||'14'||'04'  as date_id,
        channel                    as channel,
        cnline                    as prod_line,
         (case when year is null then'2021' else year end)              as year,
        '04'                       as month,
        plan_version               as plan_version,
        cast(apr as numeric(17,2)) as plan_value,
        dl_batch_date              as dl_batch_date,
        now()                      as dl_load_time
    from
        ods.r_lgc_plan_nip_dkk_portfolio
    where apr is not null
    union all
    select
         (case when year is null then'2021' else year end)||'14'||'05'    as date_id,
        channel                    as channel,
        cnline                    as prod_line,
         (case when year is null then'2021' else year end)                as year,
        '05'                       as month,
        plan_version               as plan_version,
        cast(may as numeric(17,2)) as plan_value,
        dl_batch_date              as dl_batch_date,
        now()                      as dl_load_time
    from
        ods.r_lgc_plan_nip_dkk_portfolio
    where may is not null
    union all
    select
         (case when year is null then'2021' else year end)||'14'||'06'   as date_id,
        channel                   as channel,
        cnline                    as prod_line,
         (case when year is null then'2021' else year end)               as year,
        '06'                      as month,
        plan_version              as plan_version,
        cast(jun as numeric(17,2))as plan_value,
        dl_batch_date             as dl_batch_date,
        now()                     as dl_load_time
    from
        ods.r_lgc_plan_nip_dkk_portfolio
    where jun is not null
    union all
    select
         (case when year is null then'2021' else year end)||'14'||'07'  as date_id,
        channel                  as channel,
        cnline                    as prod_line,
         (case when year is null then'2021' else year end)              as year,
        '07'                     as month,
        plan_version             as plan_version,
        cast(jul as numeric(17,2))as plan_value,
        dl_batch_date            as dl_batch_date,
        now()                    as dl_load_time
    from
        ods.r_lgc_plan_nip_dkk_portfolio
    where jul is not null
    union all
    select
         (case when year is null then'2021' else year end)||'14'||'08'  as date_id,
        channel                  as channel,
        cnline                    as prod_line,
         (case when year is null then'2021' else year end)              as year,
        '08'                     as month,
        plan_version             as plan_version,
        cast(aug as numeric(17,2))as plan_value,
        dl_batch_date            as dl_batch_date,
        now()                    as dl_load_time
    from
        ods.r_lgc_plan_nip_dkk_portfolio
    where aug is not null
    union all
    select
         (case when year is null then'2021' else year end)||'14'||'09'  as date_id,
        channel                  as channel,
        cnline                    as prod_line,
         (case when year is null then'2021' else year end)              as year,
        '09'                     as month,
        plan_version             as plan_version,
        cast(sep as numeric(17,2))as plan_value,
        dl_batch_date            as dl_batch_date,
        now()                    as dl_load_time
    from
        ods.r_lgc_plan_nip_dkk_portfolio
    where sep is not null
    union all
    select
         (case when year is null then'2021' else year end)||'14'||'10'   as date_id,
        channel                   as channel,
        cnline                    as prod_line,
         (case when year is null then'2021' else year end)               as year,
        '10'                      as month,
        plan_version              as plan_version,
        cast(oct as numeric(17,2))as plan_value,
        dl_batch_date             as dl_batch_date,
        now()                     as dl_load_time
    from
        ods.r_lgc_plan_nip_dkk_portfolio
    where oct is not null
    union all
    select
         (case when year is null then'2021' else year end)||'14'||'11'    as date_id,
        channel                   as channel,
        cnline                    as prod_line,
         (case when year is null then'2021' else year end)                as year,
        '11'                      as month,
        plan_version              as plan_version,
        cast(nov as numeric(17,2))as plan_value,
        dl_batch_date             as dl_batch_date,
        now()                     as dl_load_time
    from
        ods.r_lgc_plan_nip_dkk_portfolio
    where nov is not null
    union all
    select
         (case when year is null then'2021' else year end)||'14'||'12'   as date_id,
        channel                   as channel,
        cnline                    as prod_line,
         (case when year is null then'2021' else year end)               as year,
        '12'                      as month,
        plan_version               as plan_version,
        cast(dec as numeric(17,2)) as plan_value,
        dl_batch_date             as dl_batch_date,
        now()                     as dl_load_time
    from
        ods.r_lgc_plan_nip_dkk_portfolio
    where dec is not null;
