Staging:
  src_columns:
    store_name_key text,
    store_code text,
    store_renovation_postfix text,
    store_name_chn text,
    store_name_eng text,
    partner text,
    city text,
    city_chn text,
    cityformap text,
    city_tier text,
    admin_level text,
    city_entry_year text,
    region text,
    province text,
    province_chn text,
    landlord text,
    location_type text,
    status text,
    year text,
    quarter text,
    opening_month text,
    estimated_soft_opening_date text,
    construction_completion_date text,
    risk text,
    total_operating_weeks text,
    tony_operating_weeks text,
    jason_operating_weeks text,
    bd text,
    pm text,
    new_malls text,
    floor text,
    store_size text,
    gross_lease_area text,
    sales_area text,
    boh_area text,
    remote_storage_area text,
    store_address_chn text,
    store_address_eng text,
    wall_bays text,
    topic_of_mosaic_image text,
    lcp_model_topic text,
    shopper_profile_mall_positioning text,
    location_grade text,
    monthly_sales_grade text,
    space_grad text,
    shopper_profile_mall_location_point text,
    location_point text,
    monthly_sales_point text,
    space_point text,
    total_point text,
    store_grade text,
    cs_proj text,
    traffic_proj text,
    atv_proj text,
    cr_proj text,
    cs text,
    traffic text,
    counter_of_transaction text,
    atv text,
    cr text,
    contract_start_date text,
    contract_end_date text,
    rent_1st_year text,
    rent_2nd_year text,
    rent_3rd_year text,
    rent_4th_year text,
    rent_5th_year text,
    extra_col1 text,
    extra_col2 text,
    reduce_point_1st_year text,
    reduce_point_2nd_year text,
    reduce_point_3rd_year text,
    reduce_point_4th_year text,
    reduce_point_5th_year text,
    management_fee_1st_year text,
    management_fee_2nd_year text,
    management_fee_3rd_year text,
    management_fee_4th_year text,
    management_fee_5th_year text,
    partner_proposed_open_date text

ODS:

EDW:
  create_edw_table_query:
    create table if not exists edw.f_lgc_lcs_store_bd(
    lego_store_code        varchar(200),
    store_name_key         varchar(200),
    store_name_chn         varchar(200),
    store_name_eng         varchar(200),
    store_address_cn       varchar(200),
    store_address_en       varchar(200),
    store_renvt_postfix    varchar(200),
    customer               varchar(200),
    city                   varchar(200),
    city_chn               varchar(200),
    city_map               varchar(200),
    city_level             varchar(200),
    city_admin_level       varchar(200),
    city_entry_year        varchar(200),
    region                 varchar(200),
    province               varchar(200),
    province_cn            varchar(200),
    land_lord              varchar(200),
    location_type          varchar(200),
    status                 varchar(200),
    open_year              varchar(200),
    open_quarter           varchar(200),
    open_month             varchar(200),
    plan_open_date         varchar(200),
    cnstrct_complt_date    varchar(200),
    risk                   varchar(200),
    total_operate_week     numeric(17,0),
    tony_operate_week      numeric(17,0),
    bd                     varchar(200),
    pm                     varchar(200),
    is_new_mall            varchar(200),
    store_floor            varchar(200),
    store_size             numeric(17,2),
    gross_lease_area       numeric(17,2),
    sales_area             numeric(17,2),
    boh_area               numeric(17,2),
    remote_storage_area    numeric(17,2),
    wall_bays              varchar(200),
    mosaic_image_topic     varchar(200),
    lcp_model_topic        varchar(200),
    cntrct_start_date      varchar(200),
    cntrct_end_date        varchar(200),
    prtnr_props_open_date  varchar(200),
    dl_batch_date          varchar(20),
    dl_load_time           timestamp,
    constraint pk_f_lgc_lcs_store_bd primary key(lego_store_code)
    ); 

  delete_edw_table_query:
    delete from edw.f_lgc_lcs_store_bd;

  insert_edw_table_query:
    insert into edw.f_lgc_lcs_store_bd 
    select 
        store_code                     as lego_store_code,
        store_name_key                 as store_name_key,
        store_name_chn                 as store_name_chn,
        store_name_eng                 as store_name_eng,
        store_address_chn              as store_address_cn,
        store_address_eng              as store_address_en,
        store_renovation_postfix       as store_renvt_postfix,
        partner                        as customer,
        city                           as city,
        city_chn                       as city_chn,
        cityformap                     as city_map,
        city_tier                      as city_level,
        admin_level                    as city_admin_level,
        city_entry_year                as city_entry_year,
        region                         as region,
        province                       as province,
        province_chn                   as province_cn,
        landlord                       as land_lord,
        location_type                  as location_type,
        status                         as status,
        year                           as open_year,
        quarter                        as open_quarter,
        opening_month                  as open_month,
        estimated_soft_opening_date    as plan_open_date,
        construction_completion_date   as cnstrct_complt_date,
        risk                           as risk,
        case when (total_operating_weeks ~ E'^([0-9]+[.]?[0-9]*|[.][0-9]+)$') then cast(total_operating_weeks  as numeric(17,0)) else null end as total_operate_week,
        case when (tony_operating_weeks ~ E'^([0-9]+[.]?[0-9]*|[.][0-9]+)$') then cast(tony_operating_weeks  as numeric(17,0)) else null end as tony_operate_week,
        bd                             as bd,
        pm                             as pm,
        new_malls                      as is_new_mall,
        floor                          as store_floor,
        case when (store_size ~ E'^([0-9]+[.]?[0-9]*|[.][0-9]+)$') then cast(store_size  as numeric(17,2)) else null end as store_size,
        case when (gross_lease_area ~ E'^([0-9]+[.]?[0-9]*|[.][0-9]+)$') then cast(gross_lease_area  as numeric(17,2)) else null end as gross_lease_area,
        case when (sales_area ~ E'^([0-9]+[.]?[0-9]*|[.][0-9]+)$') then cast(sales_area  as numeric(17,2)) else null end as sales_area,
        case when (boh_area ~ E'^([0-9]+[.]?[0-9]*|[.][0-9]+)$') then cast(boh_area  as numeric(17,2)) else null end as boh_area,
        case when (remote_storage_area ~ E'^([0-9]+[.]?[0-9]*|[.][0-9]+)$') then cast(remote_storage_area  as numeric(17,2)) else null end as remote_storage_area,
        wall_bays                      as wall_bays,
        topic_of_mosaic_image          as mosaic_image_topic,
        lcp_model_topic                as lcp_model_topic,
        contract_start_date            as cntrct_start_date,
        contract_end_date              as cntrct_end_date,
        partner_proposed_open_date     as prtnr_props_open_date,
        dl_batch_date                  as dl_batch_date,
        now()                          as dl_load_time
    from
        ods.r_lgc_lcs_store_bd
    where store_code is not null;
        
  update_edw_table_query:
    update edw.d_lgc_phy_store t1 
    set store_name = case when t2.store_name_chn is null then t1.store_name else  t2.store_name_chn  end,
        customer = case when t2.Partner is null then t1.customer else  t2.Partner end ,
        store_address = case when t2.store_address_chn is null then t1.store_address  else  t2.store_address_chn end ,
        province = case when t2.province is null then t1.province else  t2.province end,
        city = case when t2.city is null then t1.city else  t2.city end,
        city_cn = case when t2.city_chn is null then t1.city_cn else  t2.city_chn end, 
        region = case when t2.region is null then t1.region else  t2.region end
    
        from
            (select distinct 
                  store_code , 
                  store_name_chn,
                  Partner,
                  store_address_chn,
                  province,
                  city,
                  city_chn,
                  region,
                  dl_batch_date
             from 
                ods.r_lgc_lcs_store_bd 
            
            )t2
        where 
           t2.store_code = t1.lego_store_code
           and upper(t1.review_channel) = 'LCS';