Staging:
  src_columns:
    channel text,
    temp_product text,
    shouldbe_product text,
    flag text
ODS:

EDW:
  create_table_query:
    create table if not exists edw.f_lgc_prod_modify
    (channel           varchar(20) not null,
     lego_sku_id_temp  varchar(50) not null,
     lego_sku_id_corrt varchar(50) ,
     modify_type       varchar(20) ,
     dl_batch_date     varchar(20) ,
     dl_load_time      timestamp,
     constraint pk_f_lgc_prod_modify primary key(channel, lego_sku_id_temp)
    )distributed by (channel);

  delete_table_query:
    delete from edw.f_lgc_prod_modify;

  insert_table_query:
    insert into edw.f_lgc_prod_modify
    select
        channel,
        temp_product     as lego_sku_id_temp,
        shouldbe_product as lego_sku_id_corrt,
        flag             as modify_type,
        dl_batch_date    as dl_batch_date,
        now()            as dl_load_time
    from
       ods.r_lgc_modified_product;