Staging:
  src_columns:
    channel_code text,
    channel_name text,
    calendar_year text,
    cs_plan_version text,
    cs_plan_month text,
    top_theme text,
    consumer_sales_plan_value text

ODS:
EDW:
  create_edw_table_query:
    create table if not exists edw.f_lgc_plan_lbr_net_dkk_portfolio
    (date_id    varchar(20),
     chnnl_code varchar(100),
     chnnl_name varchar(100),
     plan_year  varchar(20),
     plan_month varchar(20),
     plan_versn varchar(10),
     prod_them  varchar(100),
     cnsmr_sale_amt_plan numeric(17,2),
     dl_batch_date varchar(20),
     dl_load_time  timestamp,
     constraint pk_f_lgc_plan_lbr_net_dkk_portfolio primary key(chnnl_code,plan_year, plan_month, plan_versn,prod_them)
    )distributed by (plan_year);

  delete_edw_table_query:
    delete from edw.f_lgc_plan_lbr_net_dkk_portfolio;

  insert_edw_table_query:
    insert into edw.f_lgc_plan_lbr_net_dkk_portfolio
    select
        calendar_year||'14'||lpad(cs_plan_month,2,'0')   as date_id,
        channel_code                         as chnnl_code,
        channel_name                         as chnnl_name,
        calendar_year                        as plan_year,
        cs_plan_month                        as plan_month,
        cs_plan_version                      as plan_versn,
        top_theme                            as prod_them,
        consumer_sales_plan_value            as cnsmr_sale_amt_plan,
        dl_batch_date                        as dl_batch_date,
        now()                                as dl_load_time
    from
        ods.r_lgc_plan_lbr_net_dkk_portfolio
    where
        channel_name is not null;