Staging:
  src_columns:
    reviewchannel text,
    customer text,
    store_code text,
    store_name text,
    store_address text,
    citycn text,
    city text,
    province text,
    region text,
    sold_to text,
    ship_to text,
    trad_id text,
    channel_lv1 text,
    channel_lv2 text,
    channel_lv3 text,
    opendate text,
    upd_week text,
    extra_col1 text,
    extra_col2 text,
    extra_col3 text,
    extra_col4 text
ODS:

EDW:
  create_edw_table_query:
    create table if not exists edw.d_lgc_phy_store
      (sold_to varchar(200),
     ship_to varchar(200),
     trad_id varchar(200),
     lego_store_code varchar(200),
     store_name varchar(200),
     review_channel varchar(200),
     customer varchar(200),
     store_address varchar(200),
     province varchar(200),
     city varchar(200),
     city_cn varchar(200),
     region varchar(200),
     channel_lv1 varchar(200),
     channel_lv2 varchar(200),
     channel_lv3 varchar(200),
     open_date varchar(100),
     update_week varchar(100),
     dl_batch_date varchar(100),
     dl_load_time timestamp,
     constraint pk_d_lgc_phy_store primary key(review_channel,lego_store_code)
    )distributed by (review_channel);


  insert_edw_table_query:
    delete from edw.d_lgc_phy_store;
    insert into edw.d_lgc_phy_store
    select
        sold_to,
        ship_to,
        trad_id,
        lego_store_code,
        store_name,
        review_channel,
        customer,
        store_address,
        province,
        city,
        city_cn,
        region,
        channel_lv1,
        channel_lv2,
        channel_lv3,
        open_date,
        update_week,
        dl_batch_date,
        dl_load_time
    from 
       (select
            sold_to                        as sold_to,
            ship_to                        as ship_to,
            trad_id                        as trad_id,
            store_code                     as lego_store_code,
            store_name                     as store_name,
            reviewchannel                  as review_channel,
            customer                       as customer,
            case when store_address ='0' then null else store_address end as store_address,
            province                       as province,
            city                           as city,
            citycn                         as city_cn,
            region                         as region,
            channel_lv1                    as channel_lv1,
            channel_lv2                    as channel_lv2,
            channel_lv3                    as channel_lv3,
            opendate                       as open_date,
            replace(upd_week,'WK','13')    as update_week,
            dl_batch_date                  as dl_batch_date,
            now()                          as dl_load_time,
            row_number()over(partition by store_code order by opendate desc,upd_week desc) as row_num 
            
          from
            ods.r_lgc_phy_store
          where  store_code is not null  
            and ReviewChannel <>'ReviewChannel'
         )tt 
        where row_num =1 ;

  update_edw_table_query:
    update edw.d_lgc_phy_store t1 
    set store_name = case when t2.store_name_chn is null then t1.store_name else  t2.store_name_chn  end,
        customer = case when t2.Partner is null then t1.customer else  t2.Partner end ,
        store_address = case when t2.store_address_chn is null then t1.store_address  else  t2.store_address_chn end ,
        province = case when t2.province is null then t1.province else  t2.province end,
        city = case when t2.city is null then t1.city else  t2.city end,
        city_cn = case when t2.city_chn is null then t1.city_cn else  t2.city_chn end, 
        region = case when t2.region is null then t1.region else  t2.region end
        from
            (select distinct 
                  store_code , 
                  store_name_chn,
                  Partner,
                  store_address_chn,
                  province,
                  city,
                  city_chn,
                  region,
                  dl_batch_date
             from 
                ods.r_lgc_lcs_store_bd 
            
            )t2
        where 
           t2.store_code = t1.lego_store_code
           and upper(t1.review_channel) = 'LCS';