Staging:
  src_columns:
    customer text,
    month text,
    first_week text,
    second_week text,
    third_week text,
    fourth_week text,
    fifth_week text

ODS:

EDW:
  create_edw_table_query:
    create table if not exists edw.f_lgc_cs_week_phase(
       date_id           varchar(20),
       distributor_code  varchar(50),
       distributor_name  varchar(100),
       month             varchar(4),
       week_num          bigint,
       value             numeric(17,2),
       dl_batch_date     varchar(20),
       dl_load_time      timestamp,
       constraint pk_f_lgc_cs_week_phase primary key(distributor_name, month,week_num )
    )distributed by (distributor_name);



  delete_edw_table_query:
    delete from edw.f_lgc_cs_week_phase;

  insert_edw_table_query:
    insert into edw.f_lgc_cs_week_phase
    select
       month             as date_id,
       null              as distributor_code,
       customer          as distributor_name,
       month             as month,
       1                 as week_num,
       cast(first_week as numeric(17,2))as value,
       dl_batch_date     as dl_batch_date,
       now()             as dl_load_time
    from
        ods.r_lgc_cs_weekly_phasing
    union all
    select
       month             as date_id,
       null              as distributor_code,
       customer          as distributor_name,
       month             as month,
       2                 as week_num,
       cast(second_week as numeric(17,2))as value,
       dl_batch_date     as dl_batch_date,
       now()             as dl_load_time
    from
        ods.r_lgc_cs_weekly_phasing
    union all
    select
       month             as date_id,
       null              as distributor_code,
       customer          as distributor_name,
       month             as month,
       3                 as week_num,
       cast(third_week as numeric(17,2))as value,
       dl_batch_date     as dl_batch_date,
       now()             as dl_load_time
    from
        ods.r_lgc_cs_weekly_phasing
    union all
    select
       month             as date_id,
       null              as distributor_code,
       customer          as distributor_name,
       month             as month,
       4                 as week_num,
       cast(fourth_week as numeric(17,2))as value,
       dl_batch_date     as dl_batch_date,
       now()             as dl_load_time
    from
        ods.r_lgc_cs_weekly_phasing
    union all
    select
       month             as date_id,
       null              as distributor_code,
       customer          as distributor_name,
       month             as month,
       5                 as week_num,
       cast(fifth_week as numeric(17,2))as value,
       dl_batch_date     as dl_batch_date,
       now()             as dl_load_time
    from
        ods.r_lgc_cs_weekly_phasing ;
