Staging:
  src_columns:
    store text,
    close_date text,
    reopen_date text,
    reason text

ODS:

EDW:
  create_edw_table_query:
    create table if not exists edw.f_lgc_store_temporary_close_list(
    lego_store_code  varchar(200),
    close_date       varchar(200),
    reopen_date      varchar(200),
    reason           varchar(200),
    dl_batch_date    varchar(200),
    dl_load_time     timestamp,
    constraint pk_f_lgc_store_temp_close_list primary key(lego_store_code, close_date)
    )distributed by (lego_store_code);

  insert_edw_table_query:
    delete from edw.f_lgc_store_temporary_close_list;
    insert into edw.f_lgc_store_temporary_close_list(
    lego_store_code,
    close_date,
    reopen_date,
    reason,
    dl_batch_date,
    dl_load_time
    )
    select
       store                                                   as lego_store_code,
       ro_char(to_date(close_date,'mm/dd/yyyy'),'yyyy-mm-dd')  as close_date,
       ro_char(to_date(reopen_date,'mm/dd/yyyy'),'yyyy-mm-dd') as reopen_date,
       reason,
       dl_batch_date,
       now() as dl_load_time
    from ods.r_lgc_store_closure_list;
