Staging:
  src_columns:
    store_code text,
    store_name text,
    sold_to text,
    ship_to text,
    trad_id text,
    reviewchannel text,
    channel text,
    partner text,
    distributor text,
    subdistributor text,
    subdistributor_lvl1 text,
    subdistributor_lvl2 text,
    subdistributor_lvl3 text,
    region text,
    province text,
    city text,
    citycn text,
    store_address text,
    opendate text,
    upd_week text


ODS:

EDW:
  create_edw_table_query:
    create table if not exists edw.d_lgc_phy_store(
     lego_store_code           varchar(100),
     store_name                varchar(200),
     sold_to                   varchar(100),
     ship_to                   varchar(100),
     trad_id                   varchar(100),
     review_channel_name       varchar(200),
     channel_name              varchar(200),
     partner_name              varchar(200),
     distributor_name          varchar(200),
     sub_distributor_name      varchar(200),
     sub_distributor_lvl1_name varchar(200),
     sub_distributor_lvl2_name varchar(200),
     sub_distributor_lvl3_name varchar(200),
     region_name_en            varchar(200),
     provice_name_en           varchar(200),
     city_name_en              varchar(200),
     city_name_cn              varchar(200),
     store_address             varchar(200),
     open_date                 varchar(50),
     update_week               varchar(50),
     ld_batch_date             varchar(50),
     ld_load_time              timestamp,
     constraint pk_d_lgc_phy_store primary key(review_channel_name,lego_store_code)
    )distributed by (review_channel_name);


  insert_edw_table_query:
    delete from edw.d_lgc_phy_store;
    insert into edw.d_lgc_phy_store
    select
        store_code                        as lego_store_code,
        store_name                        as store_name,
        sold_to                           as sold_to,
        ship_to                           as ship_to,
        trad_id                           as trad_id,
        reviewchannel                     as review_channel_name,
        channel                           as channel_name,
        partner                           as partner_name,
        distributor                       as distributor_name ,
        subdistributor                    as sub_distributor_name ,
        subdistributor_lvl1               as sub_distributor_lvl1_name,
        subdistributor_lvl2               as sub_distributor_lvl2_name,
        subdistributor_lvl3               as sub_distributor_lvl3_name,
        region                            as region_name_en ,
        province                          as provice_name_en,
        city                              as city_name_en,
        citycn                            as city_name_cn,
        store_address                     as store_address,
        opendate                          as open_date,
        replace(upper(upd_week),'wk','13')as update_week,
        ld_batch_date                     as ld_batch_date,
        now()                             as ld_load_time    
    from ods.r_lgc_phy_store
    where store_code is not null  
      and ReviewChannel <>'ReviewChannel'；

  update_edw_table_query:
    update edw.d_lgc_phy_store t1 
    set store_name = case when t2.store_name_chn is null then t1.store_name else  t2.store_name_chn  end,
        customer = case when t2.Partner is null then t1.customer else  t2.Partner end ,
        store_address = case when t2.store_address_chn is null then t1.store_address  else  t2.store_address_chn end ,
        province = case when t2.province is null then t1.province else  t2.province end,
        city = case when t2.city is null then t1.city else  t2.city end,
        city_cn = case when t2.city_chn is null then t1.city_cn else  t2.city_chn end, 
        region = case when t2.region is null then t1.region else  t2.region end
        from
            (select distinct 
                  store_code , 
                  store_name_chn,
                  Partner,
                  store_address_chn,
                  province,
                  city,
                  city_chn,
                  region,
                  dl_batch_date
             from 
                ods.r_lgc_lcs_store_bd 
            
            )t2
        where 
           t2.store_code = t1.lego_store_code
           and upper(t1.review_channel) = 'LCS';