Staging:
  src_columns:
    customer text,
    year text,
    jan text,
    feb text,
    mar text,
    apr text,
    may text,
    jun text,
    jul text,
    aug text,
    sep text,
    oct text,
    nov text,
    dec text,
    plan_version text

ODS:

EDW:
  create_edw_table_query:
    create table if not exists edw.f_lgc_plan_nip_dkk(
    distributor_code    varchar(200),
    distributor_name    varchar(200),
    plan_lego_year    varchar(10),
    plan_lego_month    varchar(4),
    plan_version    varchar(20),
    plan_amt        numeric(17,2),
    data_version    varchar(200),
    dl_batch_date    varchar(200),
    dl_load_time    timestamp,
    constraint pk_f_lgc_plan_nip_dkk primary key(distributor_name, plan_lego_year,plan_lego_month,plan_version)
    )distributed by (plan_year);

  insert_edw_table_query:
    delete from edw.f_lgc_plan_nip_dkk;
    insert into edw.f_lgc_plan_nip_dkk
    select
        null                       as distributor_code,
        customer                   as distributor_name,
        year                       as plan_lego_year,
        '01'                       as plan_lego_month,
        plan_version               as plan_version,
        cast(jan as numeric(17,2)) as plan_amount,
        'NIP/NET DKK'              as data_version,
        dl_batch_date              as dl_batch_date,
        now()                      as dl_load_time
    from
        ods.r_lgc_plan_nip_dkk
    where
        lower(jan) <>'jan'
        and jan is not null
    union all
    select
        null                       as distributor_code,
        customer                   as distributor_name,
        year                       as plan_lego_year,
        '02'                       as plan_lego_month,
        plan_version               as plan_version,
        cast(feb as numeric(17,2)) as plan_amount,
        'NIP/NET DKK'              as data_version,
        dl_batch_date              as dl_batch_date,
        now()                      as dl_load_time
    from
        ods.r_lgc_plan_nip_dkk
    where
        lower(feb) <>'feb'
        and feb is not null
    union all
    select
        null                       as distributor_code,
        customer                   as distributor_name,
        year                       as plan_lego_year,
        '03'                       as plan_lego_month,
        plan_version               as plan_version,
        cast(mar as numeric(17,2)) as plan_amount,
        'NIP/NET DKK'              as data_version,
        dl_batch_date              as dl_batch_date,
        now()                      as dl_load_time
    from
        ods.r_lgc_plan_nip_dkk
    where
        lower(mar) <>'mar'
        and mar is not null
    union all
    select
        null                       as distributor_code,
        customer                   as distributor_name,
        year                       as plan_lego_year,
        '04'                       as plan_lego_month,
        plan_version               as plan_version,
        cast(apr as numeric(17,2)) as plan_amount,
        'NIP/NET DKK'              as data_version,
        dl_batch_date              as dl_batch_date,
        now()                      as dl_load_time
    from
        ods.r_lgc_plan_nip_dkk
    where
        lower(apr) <>'apr'
        and apr is not null
    union all
    select
        null                       as distributor_code,
        customer                   as distributor_name,
        year                       as plan_lego_year,
        '05'                       as plan_lego_month,
        plan_version               as plan_version,
        cast(may as numeric(17,2)) as plan_amount,
        'NIP/NET DKK'              as data_version,
        dl_batch_date              as dl_batch_date,
        now()                      as dl_load_time
    from
        ods.r_lgc_plan_nip_dkk
    where
        lower(may) <>'may'
        and may is not null
    union all
    select
        null                       as distributor_code,
        customer                   as distributor_name,
        year                       as plan_lego_year,
        '06'                       as plan_lego_month,
        plan_version               as plan_version,
        cast(jun as numeric(17,2)) as plan_amount,
        'NIP/NET DKK'              as data_version,
        dl_batch_date              as dl_batch_date,
        now()                      as dl_load_time
    from
        ods.r_lgc_plan_nip_dkk
    where
        lower(jun) <>'jun'
        and jun is not null
    union all
    select
        null                       as distributor_code,
        customer                   as distributor_name,
        year                       as plan_lego_year,
        '07'                       as plan_lego_month,
        plan_version               as plan_version,
        cast(jul as numeric(17,2)) as plan_amount,
        'NIP/NET DKK'              as data_version,
        dl_batch_date              as dl_batch_date,
        now()                      as dl_load_time
    from
        ods.r_lgc_plan_nip_dkk
    where
        lower(jul) <>'jul'
        and jul is not null
    union all
    select
        null                       as distributor_code,
        customer                   as distributor_name,
        year                       as plan_lego_year,
        '08'                       as plan_lego_month,
        plan_version               as plan_version,
        cast(aug as numeric(17,2)) as plan_amount,
        'NIP/NET DKK'              as data_version,
        dl_batch_date              as dl_batch_date,
        now()                      as dl_load_time
    from
        ods.r_lgc_plan_nip_dkk
    where
        lower(aug) <>'aug'
        and aug is not null
    union all
    select
        null                       as distributor_code,
        customer                   as distributor_name,
        year                       as plan_lego_year,
        '09'                       as plan_lego_month,
        plan_version               as plan_version,
        cast(sep as numeric(17,2)) as plan_amount,
        'NIP/NET DKK'              as data_version,
        dl_batch_date              as dl_batch_date,
        now()                      as dl_load_time
    from
        ods.r_lgc_plan_nip_dkk
    where
        lower(sep) <>'sep'
        and sep is not null
    union all
    select
        null                      as distributor_code,
        customer                  as distributor_name,
        year                      as plan_lego_year,
        '10'                      as plan_lego_month,
        plan_version              as plan_version,
        cast(oct as numeric(17,2))as plan_amount,
        'NIP/NET DKK'             as data_version,
        dl_batch_date             as dl_batch_date,
        now()                     as dl_load_time
    from
        ods.r_lgc_plan_nip_dkk
    where
        lower(oct) <>'oct'
        and oct is not null
    union all
    select
        null                      as distributor_code,
        customer                  as distributor_name,
        year                      as plan_lego_year,
        '11'                      as plan_lego_month,
        plan_version              as plan_version,
        cast(nov as numeric(17,2))as plan_amount,
        'NIP/NET DKK'             as data_version,
        dl_batch_date             as dl_batch_date,
        now()                     as dl_load_time
    from
        ods.r_lgc_plan_nip_dkk
    where
        lower(nov) <>'nov'
        and nov is not null
    union all
    select
        null                      as distributor_code,
        customer                  as distributor_name,
        year                      as plan_lego_year,
        '12'                      as plan_lego_month,
        plan_version              as plan_version,
        cast(dec as numeric(17,2))as plan_amount,
        'NIP/NET DKK'             as data_version,
        dl_batch_date             as dl_batch_date,
        now()                     as dl_load_time
    from
        ods.r_lgc_plan_nip_dkk
    where
        lower(dec) <>'dec'
        and dec is not null
        ;