Staging:
  src_columns:
    c6_linking_level text,
    customer_name text,
    trade_id text,
    location text,
    store_id text,
    communication_number text,
    address text,
    cst_consumer_sales_qty text,
    cst_retail_stock_nip text,
    cst_retail_stock_qty text,
    consumer_sales_net text

ODS:

EDW:
  create_table_query:
    
  
  insert_edw_from_ods_query:
    


