Staging:
  src_columns:
    channel text,
    cnline text,
    year text,
    jan text,
    feb text,
    mar text,
    apr text,
    may text,
    jun text,
    jul text,
    aug text,
    sep text,
    oct text,
    nov text,
    dec text,
    plan_version text

ODS:

EDW:
  create_edw_table_query:
    create table if not exists edw.f_lgc_plan_nip_dkk_portflio(
       channel_name   varchar(20),
       product_line   varchar(100),
       plan_year      varchar(10),
       plan_month     varchar(10),
       plan_version   varchar(20),
       plan_amount    numeric(17,2),
       data_version   varchar(100),
       dl_batch_date  varchar(10),
       dl_load_time   timestamp,
       constraint pk_f_lgc_plan_nip_dkk_portflio primary key(channel_name,product_line,plan_year,plan_month,plan_version)
    )distributed by (plan_year);

  delete_edw_table_query:
     delete from edw.f_lgc_plan_nip_dkk_portflio;

  insert_edw_table_query:
    insert into edw.f_lgc_plan_nip_dkk_portflio
    select
        channel                     as channel_name,
        cnline                      as product_line,
        year                        as plan_year,
        '01'                        as plan_month,
        plan_version                as plan_version,
        cast(jan as numeric(17,2))  as plan_amount,
        'NEP/NIP DKK'               as data_version,
        dl_batch_date               as dl_batch_date,
        now()                       as dl_load_time
    from
        ods.r_lgc_plan_nip_dkk_portfolio
    where jan is not null
    union all
    select
        channel                     as channel_name,
        cnline                      as product_line,
        year                        as plan_year,
        '02'                        as plan_month,
        plan_version                as plan_version,
        cast(feb as numeric(17,2))  as plan_amount,
        'NEP/NIP DKK'               as data_version,
        dl_batch_date               as dl_batch_date,
        now()                       as dl_load_time
    from
        ods.r_lgc_plan_nip_dkk_portfolio
    where feb is not null
    union all
    select
        channel                     as channel_name,
        cnline                      as product_line,
        year                        as plan_year,
        '03'                        as plan_month,
        plan_version                as plan_version,
        cast(mar as numeric(17,2))  as plan_amount,
        'NEP/NIP DKK'               as data_version,
        dl_batch_date               as dl_batch_date,
        now()                       as dl_load_time
    from
        ods.r_lgc_plan_nip_dkk_portfolio
    where mar is not null
    union all
    select
        channel                     as channel_name,
        cnline                      as product_line,
        year                        as plan_year,
        '04'                        as plan_month,
        plan_version                as plan_version,
        cast(apr as numeric(17,2))  as plan_amount,
        'NEP/NIP DKK'               as data_version,
        dl_batch_date               as dl_batch_date,
        now()                       as dl_load_time
    from
        ods.r_lgc_plan_nip_dkk_portfolio
    where apr is not null
    union all
    select
        channel                     as channel_name,
        cnline                      as product_line,
        year                        as plan_year,
        '05'                        as plan_month,
        plan_version                as plan_version,
        cast(may as numeric(17,2))  as plan_amount,
        'NEP/NIP DKK'               as data_version,
        dl_batch_date               as dl_batch_date,
        now()                       as dl_load_time
    from
        ods.r_lgc_plan_nip_dkk_portfolio
    where may is not null
    union all
    select
        channel                     as channel_name,
        cnline                      as product_line,
        year                        as plan_year,
        '06'                        as plan_month,
        plan_version                as plan_version,
        cast(jun as numeric(17,2))  as plan_amount,
        'NEP/NIP DKK'               as data_version,
        dl_batch_date               as dl_batch_date,
        now()                       as dl_load_time
    from
        ods.r_lgc_plan_nip_dkk_portfolio
    where jun is not null
    union all
    select
        channel                     as channel_name,
        cnline                      as product_line,
        year                        as plan_year,
        '07'                        as plan_month,
        plan_version                as plan_version,
        cast(jul as numeric(17,2))  as plan_amount,
        'NEP/NIP DKK'               as data_version,
        dl_batch_date               as dl_batch_date,
        now()                       as dl_load_time
    from
        ods.r_lgc_plan_nip_dkk_portfolio
    where jul is not null
    union all
    select
        channel                     as channel_name,
        cnline                      as product_line,
        year                        as plan_year,
        '08'                        as plan_month,
        plan_version                as plan_version,
        cast(aug as numeric(17,2))  as plan_amount,
        'NEP/NIP DKK'               as data_version,
        dl_batch_date               as dl_batch_date,
        now()                       as dl_load_time
    from
        ods.r_lgc_plan_nip_dkk_portfolio
    where aug is not null
    union all
    select
        channel                     as channel_name,
        cnline                      as product_line,
        year                        as plan_year,
        '09'                        as plan_month,
        plan_version                as plan_version,
        cast(sep as numeric(17,2))  as plan_amount,
        'NEP/NIP DKK'               as data_version,
        dl_batch_date               as dl_batch_date,
        now()                       as dl_load_time
    from
        ods.r_lgc_plan_nip_dkk_portfolio
    where sep is not null
    union all
    select
        channel                     as channel_name,
        cnline                      as product_line,
        year                        as plan_year,
        '10'                        as plan_month,
        plan_version                as plan_version,
        cast(oct as numeric(17,2))  as plan_amount,
        'NEP/NIP DKK'               as data_version,
        dl_batch_date               as dl_batch_date,
        now()                       as dl_load_time
    from
        ods.r_lgc_plan_nip_dkk_portfolio
    where oct is not null
    union all
    select
        channel                     as channel_name,
        cnline                      as product_line,
        year                        as plan_year,
        '11'                        as plan_month,
        plan_version                as plan_version,
        cast(nov as numeric(17,2))  as plan_amount,
          'NEP/NIP DKK'               as data_version,
        dl_batch_date               as dl_batch_date,
        now()                       as dl_load_time
    from
        ods.r_lgc_plan_nip_dkk_portfolio
    where nov is not null
    union all
    select
        channel                     as channel_name,
        cnline                      as product_line,
        year                        as plan_year,
        '12'                        as plan_month,
        plan_version                as plan_version,
        cast(dec as numeric(17,2))  as plan_amount,
          'NEP/NIP DKK'               as data_version,
        dl_batch_date               as dl_batch_date,
        now()                       as dl_load_time
    from
        ods.r_lgc_plan_nip_dkk_portfolio
    where dec is not null;
