Staging:
  src_columns:
    customer text,
    correct_customer text



ODS:

EDW:
  create_edw_table_query:
    create table if not exists edw.f_lgc_cust_name_map
    (cust_name_temp varchar(100),
     cust_name_new varchar(100),
     ld_batch_date varchar(20),
     ld_load_time timestamp,
     constraint pk_f_lgc_cust_name_map primary key(cust_name_temp, cust_name_new)
    )distributed by (cust_name_temp);

  delete_edw_table_query:
    delete from edw.ods.r_lgc_customer_name_mapping;

  insert_edw_table_query:
    insert into edw.f_lgc_cust_name_map
      (
       cust_name_temp,
       cust_name_new,
       dl_batch_date,
       dl_load_time
      )
    select
        customer         as cust_name_temp,
        correct_customer as cust_name_new,
        dl_batch_date,
        now()            as dl_load_time
    from
       ods.r_lgc_customer_name_mapping;
