Staging:
  src_columns:
    year_week text,
    cust_link text,
    cust_name text,
    cust_id text,
    sales_district text,
    cust_loca text,
    store_id text,
    prod_id text,
    prod_name text,
    cst_cnsmr_sale_rrp text,
    cst_cnsmr_sale_qty text,
    cst_retail_stock_qty text,
    cst_retail_stock_rrp text

ODS:

EDW:
  create_edw_table_query:
    create table if not exists edw.f_lgc_sales_stock_rrp_rmb
      (sales_lego_year_week                   varchar(20),
       c6_linking_distributor_code            varchar(200),
       c6_linking_distributor_name            varchar(200),
       distributor_code         varchar(200),
       distributor_name         varchar(200),
       sales_district           varchar(200),
       sales_location           varchar(200),
       lego_store_code          varchar(200),
       lego_sku_id              varchar(50),
       lego_sku_name_en         varchar(200),
       consumer_sales_amt       numeric(17,2),
       consumer_sales_qty       bigint,
       retail_stock_amt         bigint,
       retail_stock_qty         numeric(17,2),
       qty_unit                 varchar(10),
       dl_batch_date            varchar(200),
       dl_load_time             timestamp,
       constraint pk_f_lgc_sales_stock_rrp_rmb primary key(sales_lego_year_week, distributor_code,lego_store_code,lego_sku_id)
    );

  insert_edw_table_query:
    delete from edw.f_lgc_sales_stock_rrp_rmb;
    insert into edw.f_lgc_sales_stock_rrp_rmb
    select
       split_part(year_week ,'.',2)||'13'||split_part(year_week ,'.',1) as sales_lego_year_week,
       cust_link                    as c6_linking_distributor_code,
       cust_name                    as c6_linking_distributor_name,
       cust_id                      as distributor_code,
       replace(cust_name,'6 CN ','')as distributor_name,
       sales_district               as sales_district,
       cust_loca                    as sales_location,
       store_id                     as lego_store_code,
       prod_id                      as lego_sku_id,
       prod_name                    as lego_sku_name_en,
       cast(cst_cnsmr_sale_rrp as numeric(17,2))    as consumer_sales_amt,
       cast(cst_cnsmr_sale_qty as int)              as consumer_sales_qty,
       cast(cst_retail_stock_rrp as numeric(17,2))  as retail_stock_amt,
       cast(cst_retail_stock_qty as int)            as retail_stock_qty,
       'PC'                    as qty_unit,
       dl_batch_date           as dl_batch_date,
       now()                   as dl_load_time
    from
       ods.r_lgc_sales_stock_rrp_rmb
    where
       cust_id is  not null
       and store_id is not null
       and prod_id is not null
       and cst_cnsmr_sale_qty <> 'PC';