Staging:
  src_columns:
    store_name_key text,
    store_code text,
    store_renovation_postfix text,
    store_name_chn text,
    store_name_eng text,
    partner text,
    city text,
    city_chn text,
    cityformap text,
    city_tier text,
    admin_level text,
    city_entry_year text,
    region text,
    province text,
    province_chn text,
    landlord text,
    location_type text,
    status text,
    year text,
    quarter text,
    opening_month text,
    estimated_soft_opening_date text,
    construction_completion_date text,
    risk text,
    total_operating_weeks text,
    tony_operating_weeks text,
    jason_operating_weeks text,
    bd text,
    pm text,
    new_malls text,
    floor text,
    store_size text,
    gross_lease_area text,
    sales_area text,
    boh_area text,
    remote_storage_area text,
    store_address_chn text,
    store_address_eng text,
    wall_bays text,
    topic_of_mosaic_image text,
    lcp_model_topic text,
    shopper_profile_mall_positioning text,
    location_grade text,
    monthly_sales_grade text,
    space_grad text,
    shopper_profile_mall_location_point text,
    location_point text,
    monthly_sales_point text,
    space_point text,
    total_point text,
    store_grade text,
    cs_proj text,
    traffic_proj text,
    atv_proj text,
    cr_proj text,
    cs text,
    traffic text,
    counter_of_transaction text,
    atv text,
    cr text,
    contract_start_date text,
    contract_end_date text,
    rent_1st_year text,
    rent_2nd_year text,
    rent_3rd_year text,
    rent_4th_year text,
    rent_5th_year text,
    reduce_point_1st_year text,
    reduce_point_2nd_year text,
    reduce_point_3rd_year text,
    reduce_point_4th_year text,
    reduce_point_5th_year text,
    management_fee_1st_year text,
    management_fee_2nd_year text,
    management_fee_3rd_year text,
    management_fee_4th_year text,
    management_fee_5th_year text,
    partner_proposed_open_date text

ODS:

EDW:
  create_table_query:
    
  
  insert_edw_from_ods_query:

