Staging:
  src_columns:
    year_week text,
    cust_link text,
    cust_name text,
    cust_id text,
    sale_district text,
    cust_loca text,
    store_id text,
    prod_id text,
    prod_name text,
    cst_cnsmr_sale_qty text,
    cst_retail_stock_nip text,
    cst_retail_stock_qty text,
    cnsmr_sale_nip_net text

ODS:

EDW:
  create_edw_table_query:
    create table if not exists edw.f_lgc_sales_stock_nip_dkk
      (date_id                 varchar(20),
       lego_year_week          varchar(20),
       distributor_code        varchar(20),
       distributor_name        varchar(100),
       sale_district            varchar(100),
       lego_store_code         varchar(200),
       lego_sku_id             varchar(200),
       dist_cnsmr_sale_qty     bigint,
       dist_cnsmr_sale_nip_net numeric(17,2),
       dist_retail_stock_qty   bigint,
       dist_retail_stock_nip   numeric(17,2),
       qty_unit                varchar(20),
       dl_batch_date           varchar(20),
       dl_load_time            timestamp,
       constraint pk_f_lgc_sales_stock_nip_dkk primary key(lego_year_week, lego_store_code,lego_sku_id)
    )distributed by (lego_year_week);

  delete_edw_table_query:
    delete from edw.f_lgc_sales_stock_nip_dkk;

  insert_edw_table_query:
    insert into edw.f_lgc_sales_stock_nip_dkk
    select
        split_part(year_week ,'.',2)||'13'||split_part(year_week ,'.',1) as date_id
       ,split_part(year_week ,'.',2)||'13'||split_part(year_week ,'.',1) as lego_year_week
       ,cust_id                      as distributor_code
       ,cust_name                    as distributor_name
       ,sale_district                as sale_district
       ,store_id                     as lego_store_code
       ,prod_id                      as lego_sku_id
       ,cast(cst_cnsmr_sale_qty as int)           as dist_cnsmr_sale_qty
       ,cast(cnsmr_sale_nip_net as numeric(17,2)) as dist_cnsmr_sale_nip_net
       ,cast(cst_retail_stock_qty as int)         as dist_retail_stock_qty
       ,cast(cst_retail_stock_nip as numeric(17,2)) as dist_retail_stock_nip
       ,'PC'                         as qty_unit
       ,dl_batch_date                as dl_batch_date
       ,now()                        as dl_load_time
    from
        ods.r_lgc_sales_stock_nip_dkk
    where
        cust_id is  not null
        and prod_id is not null
        and cst_cnsmr_sale_qty <> 'PC';