Staging:
  src_columns:
    reviewchannel text,
    customer text,
    store_code text,
    store_name text,
    store_address text,
    citycn text,
    city text,
    province text,
    region text,
    sold_to text,
    ship_to text,
    trad_id text,
    channel_lv1 text,
    channel_lv2 text,
    channel_lv3 text,
    opendate text,
    upd_week text,
    extra_col1 text,
    extra_col2 text,
    extra_col3 text

ODS:

EDW:
  create_edw_table_query:
    create table if not exists edw.f_lgc_phy_store
      (sold_to varchar(100),
     ship_to varchar(100),
     trad_id varchar(100),
     lego_store_code varchar(100),
     store_name varchar(100),
     review_channel varchar(100),
     customer varchar(100),
     store_address varchar(200),
     provice varchar(100),
     city varchar(100),
     city_cn varchar(100),
     region varchar(100),
     channel_lv1 varchar(100),
     channel_lv2 varchar(100),
     channel_lv3 varchar(100),
     open_date varchar(20),
     update_week varchar(20),
     ld_batch_date varchar(20),
     ld_load_time timestamp,
     constraint pk_f_lgc_phy_store primary key(lego_store_code)
    )distributed by (review_channel);

  delete_edw_table_query:
    delete from edw.f_lgc_phy_store;

  insert_edw_table_query:
    insert into edw.f_lgc_phy_store
      select
        sold_to                        as sold_to,
        ship_to                        as ship_to,
        trad_id                        as trad_id,
        store_code                     as lego_store_code,
        store_name                     as store_name,
        reviewchannel                  as review_channel,
        customer                       as customer,
        store_address                  as store_address,
        province                       as province,
        city                           as city,
        citycn                         as city_cn,
        region                         as region,
        channel_lv1                    as channel_lv1,
        channel_lv2                    as channel_lv2,
        channel_lv3                    as channel_lv3,
        to_char(to_date(opendate,'dd/mm/yyyy'),'yyyymmdd') as open_date,
        replace(upd_week,'WK','13') as update_week,
        dl_batch_date                  as dl_batch_date,
        now()                          as dl_load_time
      from
        ods.r_lgc_phy_store;