Staging:
  src_columns:
    customer text,
    month text,
    first_week text,
    second_week text,
    third_week text,
    fourth_week text,
    fifth_week text

ODS:

EDW:
  create_table_query:
    create table if not exists edw.f_lgc_cs_weekly_phasing(
      distributor_code varchar(100),
      distributor_name varchar(100),
      month varchar(20),
      week_num bigint,
      plan_value double,
      ld_batch_date varchar(20),
      ld_load_time timestampe,
      constraint pk_f_lgc_cs_weekly_phasing primary key(distributor_name, month,week_num)
    )distributed by (store_code);


  insert_edw_from_ods_query:
    insert into table edw.f_lgc_cs_weekly_phasing
      (distributor_code,
      distributor_name,
      month,
      week_num,
      plan_value,
      ld_batch_date,
      ld_load_time
      )
    select
       null            as store_code,
       customer        as distributor_name,
       month           as month,
       1               as week_num,
       first_week      as plan_value
       dl_batch_date   as dl_batch_date,
       now()           as dl_load_time
    from 
	    ods.r_lgc_cs_weekly_phasing
	where 
	   first_week is not null
       
	union all
    select
       null            as store_code,
       customer        as distributor_name,
       month           as month,
       2               as week_num,
       second_week     as plan_value
       dl_batch_date   as dl_batch_date,
       now()           as dl_load_time
    from 
	    ods.r_lgc_cs_weekly_phasing
	where 
	   second_week is not null
	union all
    select
       null            as store_code,
       customer        as distributor_name,
       month           as month,
       3               as week_num,
       third_week      as plan_value
       dl_batch_date   as dl_batch_date,
       now()           as dl_load_time
    from 
	    ods.r_lgc_cs_weekly_phasing	
	where 
	   third_week is not null
		
	union all
    select
       null            as store_code,
       customer        as distributor_name,
       month           as month,
       4               as week_num,
       fourth_week     as plan_value
       dl_batch_date   as dl_batch_date,
       now()           as dl_load_time
    from 
	    ods.r_lgc_cs_weekly_phasing	
	where 
	   fourth_week is not null
	   
	union all
    select
       null            as store_code,
       customer        as distributor_name,
       month           as month,
       5               as week_num,
       fifth_week     as plan_value
       dl_batch_date   as dl_batch_date,
       now()           as dl_load_time
    from 
	    ods.r_lgc_cs_weekly_phasing	
	where 
	   fifth_week is not null;