Staging:
  src_columns:
    store_code text,
    store_name text,
    sold_to text,
    ship_to text,
    trad_id text,
    reviewchannel text,
    channel text,
    partner text,
    distributor text,
    subdistributor text,
    subdistributor_lvl1 text,
    subdistributor_lvl2 text,
    subdistributor_lvl3 text,
    region text,
    province text,
    city text,
    citycn text,
    store_address text,
    opendate text,
    upd_week text,
    extra_col1 text,
    extra_col2 text,
    extra_col3 text,
    extra_col4 text

ODS:

EDW:
  create_edw_table_query:
    create table if not exists edw.d_lgc_phy_store(
     lego_store_code           varchar(200),
     store_name_cn             varchar(200),
     store_name_en             varchar(200),
     sold_to                   varchar(200),
     ship_to                   varchar(200),
     trad_id                   varchar(200),
     review_channel_name       varchar(200),
     channel_name              varchar(200),
     partner_name              varchar(200),
     distributor_name          varchar(200),
     sub_distributor_name      varchar(200),
     sub_distributor_lvl1_name varchar(200),
     sub_distributor_lvl2_name varchar(200),
     sub_distributor_lvl3_name varchar(200),
     region_en                 varchar(200),
     province_en               varchar(200),
     city_en                   varchar(200),
     city_cn                   varchar(200),
     store_address_cn          varchar(200),
     open_date                 varchar(200),
     update_week               varchar(200),
     dl_batch_date             varchar(200),
     dl_load_time              timestamp,
     constraint pk_d_lgc_phy_store primary key(review_channel_name,lego_store_code)
    )distributed by (review_channel_name);


  insert_edw_table_query:
    delete from edw.d_lgc_phy_store;
    insert into edw.d_lgc_phy_store
    select
        store_code                        as lego_store_code,
        store_name                        as store_name_cn,
        null                              as store_name_en
        sold_to                           as sold_to,
        ship_to                           as ship_to,
        trad_id                           as trad_id,
        reviewchannel                     as review_channel_name,
        channel                           as channel_name,
        partner                           as partner_name,
        distributor                       as distributor_name ,
        subdistributor                    as sub_distributor_name ,
        subdistributor_lvl1               as sub_distributor_lvl1_name,
        subdistributor_lvl2               as sub_distributor_lvl2_name,
        subdistributor_lvl3               as sub_distributor_lvl3_name,
        region                            as region_en ,
        province                          as province_en,
        city                              as city_en,
        citycn                            as city_cn,
        store_address                     as store_address_cn,
        substring(opendate,1,10)          as open_date,
        replace(upper(upd_week),'WK','13')as update_week,
        dl_batch_date                     as dl_batch_date,
        now()                             as dl_load_time    
    from ods.r_lgc_phy_store
    where store_code is not null  
      and ReviewChannel <>'ReviewChannel';

  update_edw_table_query:
    update edw.d_lgc_phy_store t1 
    set store_name_cn = case when t2.store_name_cn is null then t1.store_name_cn else  t2.store_name_cn  end,
        store_name_en = case when t2.store_name_en is null then t1.store_name_en else  t2.store_name_en  end,
        partner_name = case when t2.partner_name is null then t1.partner_name else  t2.partner_name end ,
        store_address_cn = case when t2.store_address_cn is null then t1.store_address_cn  else  t2.store_address_cn end ,
        province_en = case when t2.province_en is null then t1.province_en else  t2.province_en end,
        city_en = case when t2.city_en is null then t1.city_en else  t2.city_en end,
        city_cn = case when t2.city_cn is null then t1.city_cn else  t2.city_cn end, 
        region_en = case when t2.region_en is null then t1.region_en else  t2.region_en end
        from
            (select distinct 
                  lego_store_code , 
                  store_name_cn,
                  store_name_en,
                  partner_name,
                  store_address_cn,
                  province_en,
                  city_en,
                  city_cn,
                  region_en,
                  dl_batch_date
             from 
                edw.f_lgc_lcs_store_bd
            
            )t2
        where 
           t2.lego_store_code = t1.lego_store_code
           and upper(t1.channel_name) = upper('LCS');