Staging:
  src_columns:
    id text,
    platform text,
    shopid text,
    shop_name text,
    deal_code text,
    import_deal_code text,
    old_deal_code text,
    dzd_type_id text,
    dzd_type_name text,
    lego_sku_name text,
    balance text,
    fee_amount text,
    accounts_no text,
    order_no text,
    merchant_order_no text,
    self_user_id text,
    opt_user_id text,
    remark text,
    create_time text,
    category text,
    is_shougong text,
    import_time text,
    deal_status text,
    check_status text,
    is_check text,
    message text,
    bus_type text,
    bus_desc text,
    bus_sour text,
    channel text,
    dzd_dj_id text,
    error_times text,
    error_info text,
    check_time text,
    reason_diff text,
    diff_amount text,
    alipay text,
    is_cart_charge text,
    cart_money text,
    is_cart text,
    lastchanged text,
    flag text,
    sendout_time text

ODS:

EDW:
  create_table_query:
    create table if not exists edw.f_oms_expense_statement(
      id varchar(255) not null,
      platform varchar(255),
      shopid varchar(255),
      shop_name varchar(255),
      deal_code varchar(255),
      import_deal_code varchar(255),
      old_deal_code varchar(255),
      dzd_type_id varchar(255),
      dzd_type_name varchar(255),
      lego_sku_name varchar(255),
      balance decimal(17,2),
      fee_amount decimal(17,2),
      accounts_no varchar(255),
      order_no varchar(255),
      merchant_order_no varchar(255),
      self_user_id varchar(255),
      opt_user_id varchar(255),
      remark varchar(255),
      create_time varchar(255),
      category varchar(255),
      is_shougong varchar(255),
      import_time timestamp,
      deal_status varchar(255),
      check_status varchar(255),
      is_check varchar(255),
      message varchar(255),
      bus_type varchar(255),
      bus_desc varchar(255),
      bus_sour varchar(255),
      channel varchar(255),
      dzd_dj_id varchar(255),
      error_times decimal(15),
      error_info varchar(255),
      check_time timestamp,
      reason_diff varchar(255),
      diff_amount decimal(17,2),
      alipay varchar(255),
      is_cart_charge varchar(255),
      cart_money decimal(17,2),
      is_cart varchar(255),
      lastchanged timestamp,
      flag varchar(255),
      sendout_time timestamp,
      dl_batch_date varchar(8),
      dl_load_time timestamp
    )distributed by (id);

  insert_edw_from_ods_query:
    insert into edw.f_oms_expense_statement(
      id,
      platform,
      shopid,
      shop_name,
      deal_code,
      import_deal_code,
      old_deal_code,
      dzd_type_id,
      dzd_type_name,
      lego_sku_name,
      balance,
      fee_amount,
      accounts_no,
      order_no,
      merchant_order_no,
      self_user_id,
      opt_user_id,
      remark,
      create_time,
      category,
      is_shougong,
      import_time,
      deal_status,
      check_status,
      is_check,
      message,
      bus_type,
      bus_desc,
      bus_sour,
      channel,
      dzd_dj_id,
      error_times,
      error_info,
      check_time,
      reason_diff,
      diff_amount,
      alipay,
      is_cart_charge,
      cart_money,
      is_cart,
      lastchanged,
      flag,
      sendout_time,
      dl_batch_date,
      dl_load_time
    )
    select 
      id,
      platform,
      shopid,
      shop_name,
      deal_code,
      import_deal_code,
      old_deal_code,
      dzd_type_id,
      dzd_type_name,
      lego_sku_name,
      balance::decimal(17,2),
      fee_amount::decimal(17,2),
      accounts_no,
      order_no,
      merchant_order_no,
      self_user_id,
      opt_user_id,
      remark,
      to_timestamp(create_time, 'yyyy-MM-dd hh:mi:ss')  as create_time,
      category,
      is_shougong,
      to_timestamp(import_time, 'yyyy-MM-dd hh:mi:ss')  as import_time,
      case when deal_status ='0' then '开启' 
        when deal_status ='1' then '关闭'
        else null end as deal_status,
      case when check_status ='0' then '未对账' 
        when check_status ='1' then '已对账'
        else null end as check_status,
      case when is_check ='0' then '未参与' 
        when is_check ='1' then '已参与'
        else null end as is_check,
      message,
      bus_type,
      bus_desc,
      bus_sour,
      channel,
      dzd_dj_id,
      error_times::decimal(15),
      error_info,
      to_timestamp(check_time, 'yyyy-MM-dd hh:mi:ss')  as check_time,
      reason_diff,
      diff_amount::decimal(17,2),
      alipay,
      case when is_cart_charge ='0' then '否' 
        when is_cart_charge ='1' then '是'
        else null end as is_cart_charge,
      cart_money::decimal(17,2),
      case when is_cart ='0' then '否' 
        when is_cart ='1' then '是'
        else null end as is_cart,
      to_timestamp(lastchanged, 'yyyy-MM-dd hh:mi:ss')  as lastchanged,
      flag,
      to_timestamp(sendout_time, 'yyyy-MM-dd hh:mi:ss')  as sendout_time,
      dl_batch_date,
      now()
    from (
      select * , row_number() over( partition by id order by to_timestamp(sendout_time, 'yyyy-MM-dd hh:mi:ss') desc ) rk
      from ods.r_oms_expense_statement
    )ab
    where rk=1;

  sync_to_rds_dm:
    create table if not exists dm.f_oms_expense_statement (like frn.f_oms_expense_statement);
    delete from dm.f_oms_expense_statement;
    delete from dm.f_oms_expense_statement;
    insert into dm.f_oms_expense_statement select * from frn.f_oms_expense_statement;
    
  