Staging:
  src_columns:
    id text,
    platform text,
    shopid text,
    shop_name text,
    deal_code text,
    import_deal_code text,
    old_deal_code text,
    dzd_type_id text,
    dzd_type_name text,
    lego_sku_name text,
    balance text,
    fee_amount text,
    accounts_no text,
    order_no text,
    merchant_order_no text,
    self_user_id text,
    opt_user_id text,
    remark text,
    create_time text,
    category text,
    is_shougong text,
    import_time text,
    deal_status text,
    check_status text,
    is_check text,
    message text,
    bus_type text,
    bus_desc text,
    bus_sour text,
    channel text,
    dzd_dj_id text,
    error_times text,
    error_info text,
    check_time text,
    reason_diff text,
    diff_amount text,
    alipay text,
    is_cart_charge text,
    cart_money text,
    is_cart text,
    lastchanged text,
    flag text,
    sendout_time text,
    tmall_u_order text

ODS:

EDW:
  create_table_query:
    create table if not exists edw.f_oms_expense_statement(
      id varchar(255) not null,
      platform varchar(255),
      shopid varchar(255),
      shop_name varchar(255),
      deal_code varchar(255),
      import_deal_code varchar(255),
      old_deal_code varchar(255),
      dzd_type_id varchar(255),
      dzd_type_name varchar(255),
      lego_sku_name varchar(255),
      balance decimal(17,2),
      fee_amount decimal(17,2),
      accounts_no varchar(255),
      order_no varchar(255),
      merchant_order_no varchar(255),
      self_user_id varchar(255),
      opt_user_id varchar(255),
      remark varchar(255),
      create_time timestamp,
      category varchar(255),
      is_shougong varchar(255),
      import_time timestamp,
      deal_status varchar(255),
      check_status varchar(255),
      is_check varchar(255),
      message varchar(255),
      bus_type varchar(255),
      bus_desc varchar(255),
      bus_sour varchar(255),
      channel varchar(255),
      dzd_dj_id varchar(255),
      error_times decimal(15),
      error_info varchar(255),
      check_time timestamp,
      reason_diff varchar(255),
      diff_amount decimal(17,2),
      alipay varchar(255),
      is_cart_charge varchar(255),
      cart_money decimal(17,2),
      is_cart varchar(255),
      lastchanged timestamp,
      flag varchar(255),
      sendout_time timestamp,
      tmall_u_order varchar(255),
      dl_batch_date varchar(8),
      dl_load_time timestamp
    )distributed by (id);

  insert_edw_from_ods_query:
    insert into edw.f_oms_expense_statement(
      id,
      platform,
      shopid,
      shop_name,
      deal_code,
      import_deal_code,
      old_deal_code,
      dzd_type_id,
      dzd_type_name,
      lego_sku_name,
      balance,
      fee_amount,
      accounts_no,
      order_no,
      merchant_order_no,
      self_user_id,
      opt_user_id,
      remark,
      create_time,
      category,
      is_shougong,
      import_time,
      deal_status,
      check_status,
      is_check,
      message,
      bus_type,
      bus_desc,
      bus_sour,
      channel,
      dzd_dj_id,
      error_times,
      error_info,
      check_time,
      reason_diff,
      diff_amount,
      alipay,
      is_cart_charge,
      cart_money,
      is_cart,
      lastchanged,
      flag,
      sendout_time,
      tmall_u_order,
      dl_batch_date,
      dl_load_time
    )
    select 
      id,
      case when platform ='1' then '淘宝' 
        when platform ='5' then '京东'
        else '其它' end as platform,
      shopid,
      shop_name,
      case when trim(deal_code) in ('null', '') then null else deal_code end as deal_code,
      case when trim(import_deal_code) in ('null', '') then null else import_deal_code end as import_deal_code,
      case when trim(old_deal_code) in ('null', '') then null else old_deal_code end as old_deal_code,
      dzd_type_id,
      case when trim(dzd_type_name) in ('null', '') then null else dzd_type_name end as dzd_type_name,
      case when trim(lego_sku_name) in ('null', '') then null else lego_sku_name end as lego_sku_name,
      balance::decimal(17,2),
      fee_amount::decimal(17,2),
      case when trim(accounts_no) in ('null', '') then null else accounts_no end as accounts_no,
      case when trim(order_no) in ('null', '') then null else order_no end as order_no,
      case when trim(merchant_order_no) in ('null', '') then null else merchant_order_no end as merchant_order_no,
      case when trim(self_user_id) in ('null', '') then null else self_user_id end as self_user_id,
      case when trim(opt_user_id) in ('null', '') then null else opt_user_id end as opt_user_id,
      case when trim(remark) in ('null', '') then null else remark end as remark,
      case when trim(create_time) in ('null', '') then null else to_timestamp(create_time, 'yyyy-MM-dd hh24:mi:ss') end as create_time,  
      case when category ='5' then '第三方收付款' 
        when category ='6' then '随单费用'
        when category ='7' then '非随单费用'
        else category end as category,
       case when is_shougong ='0' then '否' 
        when is_shougong ='1' then '是'
        else null end as is_shougong,
      case when trim(import_time) in ('null', '') then null else to_timestamp(import_time, 'yyyy-MM-dd hh24:mi:ss') end as import_time,
      case when deal_status ='0' then '开启' 
        when deal_status ='1' then '关闭'
        else null end as deal_status,
      case when check_status ='0' then '未对账' 
        when check_status ='1' then '已对账'
        when check_status ='2' then '对账失败'
        else null end as check_status,
      case when is_check ='0' then '未参与' 
        when is_check ='1' then '已参与'
        else null end as is_check,
      case when trim(message) in ('null', '') then null else message end as message,
      case when trim(bus_type) in ('null', '') then null else bus_type end as bus_type,
      case when trim(bus_desc) in ('null', '') then null else bus_desc end as bus_desc,
      case when trim(bus_sour) in ('null', '') then null else bus_sour end as bus_sour,
      case when trim(channel) in ('null', '') then null else channel end as channel,
      dzd_dj_id,
      error_times::decimal(15),
      case when trim(error_info) in ('null', '') then null else error_info end as error_info,
      case when trim(check_time) in ('null', '') then null else to_timestamp(check_time, 'yyyy-MM-dd hh24:mi:ss') end as check_time,
      case when trim(reason_diff) in ('null', '') then null else reason_diff end as reason_diff,
      diff_amount::decimal(17,2),
      case when trim(alipay) in ('null', '') then null else alipay end as alipay,
      case when is_cart_charge ='0' then '否' 
        when is_cart_charge ='1' then '是'
        else null end as is_cart_charge,
      cart_money::decimal(17,2),
      case when is_cart ='0' then '否' 
        when is_cart ='1' then '是'
        else null end as is_cart,
      case when trim(lastchanged) in ('null', '') then null else to_timestamp(lastchanged, 'yyyy-MM-dd hh24:mi:ss') end as lastchanged,
      flag,
      case when trim(sendout_time) in ('null', '') then null else to_timestamp(sendout_time, 'yyyy-MM-dd hh24:mi:ss') end as sendout_time,
      case when tmall_u_order = '1' then '是' else '否' end as tmall_u_order,
      dl_batch_date,
      now()
    from (
      select * , row_number() over( partition by id, flag order by to_timestamp(lastchanged, 'yyyy-MM-dd hh24:mi:ss') desc ) rk
      from ods.r_oms_expense_statement
    )ab
    where rk=1;

  sync_to_rds_dm:
    create table if not exists dm.f_oms_expense_statement (like frn.f_oms_expense_statement);
    delete from dm.f_oms_expense_statement;
    delete from dm.f_oms_expense_statement;
    with del_ids as 
    ( 
      select distinct id
      from frn.f_oms_expense_statement
      where flag='DELETE'
    ),
    upd_ids as 
    (
      select 
        id,
        platform,
        shopid,
        shop_name,
        deal_code,
        import_deal_code,
        old_deal_code,
        dzd_type_id,
        dzd_type_name,
        lego_sku_name,
        balance,
        fee_amount,
        accounts_no,
        order_no,
        merchant_order_no,
        self_user_id,
        opt_user_id,
        remark,
        create_time,
        category,
        is_shougong,
        import_time,
        deal_status,
        check_status,
        is_check,
        message,
        bus_type,
        bus_desc,
        bus_sour,
        channel,
        dzd_dj_id,
        error_times,
        error_info,
        check_time,
        reason_diff,
        diff_amount,
        alipay,
        is_cart_charge,
        cart_money,
        is_cart,
        lastchanged,
        flag,
        sendout_time,
        dl_batch_date,
        dl_load_time,
        tmall_u_order
      from (
        select *, row_number() over(partition by id order by lastchanged desc) as rk
        from frn.f_oms_expense_statement es
        where flag='UPDATE'
      )t where rk =1
    )
    insert into dm.f_oms_expense_statement
    select *
    from frn.f_oms_expense_statement a
    where flag='INSERT'
    and not exists( select 1 from del_ids  where id = a.id )
    and not exists( select 1 from upd_ids  where id = a.id )
    union all
    select *
    from upd_ids a
    where not exists( select 1 from del_ids  where id = a.id );
    
  