Staging:
  src_columns:
    parent_order_id text,
    member_id text,
    is_multiple_paid text,
    payment_time text,
    distributor text,
    lego_store_code text,
    distributor_store_code text,
    store_name text,
    is_special_sales text,
    special_sales_type text,
    sale_channel text,
    piece_cnt text,
    discount_amt text,
    actual_order_amt text,
    operator_id text,
    note text,
    order_create_time text,
    order_end_time text,
    sendout_time text

ODS:    

EDW:
  create_table_query:
    CREATE TABLE if not exists edw.f_phy_store_order (
      parent_order_id varchar(255) NOT NULL,
      member_id varchar(255) NOT NULL,
      is_multiple_paid varchar(5) NULL,
      payment_time timestamp NULL,
      distributor varchar(255) NULL,
      lego_store_code varchar(255) NULL,
      distributor_store_code varchar(255) NULL,
      store_name varchar(255) NULL,
      is_special_sales varchar(255) NULL,
      special_sales_type varchar(255) NULL,
      sale_channel varchar(255) NULL,
      piece_cnt decimal(15) NULL,
      discount_amt decimal(17,2) NULL,
      actual_order_amt decimal(17,2) NULL,
      operator_id varchar(255) NULL,
      note varchar(600) NULL,
      order_create_time timestamp NULL,
      order_end_time timestamp NULL,
      sendout_time timestamp NULL,
      dl_batch_date varchar(8),
      dl_load_time timestamp
    )distributed by (distributor, parent_order_id);

  insert_edw_from_ods_query:
    insert into edw.f_phy_store_order(
      parent_order_id,
      member_id,
      is_multiple_paid,
      payment_time,
      distributor,
      lego_store_code,
      distributor_store_code,
      store_name,
      is_special_sales,
      special_sales_type,
      sale_channel,
      piece_cnt,
      discount_amt,
      actual_order_amt,
      operator_id,
      note,
      order_create_time,
      order_end_time,
      sendout_time,
      dl_batch_date,
      dl_load_time
    )select 
      parent_order_id,
      member_id,
      is_multiple_paid,
      TIMESTAMP WITH TIME ZONE 'epoch' + payment_time::decimal(13) * INTERVAL '1 s',
      upper(distributor),
      case when trim(lego_store_code) in('','null') then null else lego_store_code end as lego_store_code,
      distributor_store_code,
      store_name,
      case when trim(is_special_sales) in('','null') then null else is_special_sales end as is_special_sales,
      case when trim(special_sales_type) in('','null') then null else special_sales_type end as special_sales_type,
      case when trim(sale_channel) in('','null') then null else sale_channel end as sale_channel,
      piece_cnt::decimal(15),
      discount_amt::decimal(17,2),
      actual_order_amt::decimal(17,2),
      operator_id,
      note,
      TIMESTAMP WITH TIME ZONE 'epoch' + order_create_time::decimal(13) * INTERVAL '1 s',
      case when order_end_time in ('null','') then null else TIMESTAMP WITH TIME ZONE 'epoch' + order_end_time::decimal(13) * INTERVAL '1 s'end,
      TIMESTAMP WITH TIME ZONE 'epoch' + sendout_time::decimal(13) * INTERVAL '1 s',
      dl_batch_date,
      dl_load_time
    from (
      select * , row_number() over( partition by upper(distributor), distributor_store_code, parent_order_id order by (TIMESTAMP WITH TIME ZONE 'epoch' + sendout_time::decimal(13) * INTERVAL '1 s') desc ) rk
      from ods.r_phy_store_order
    )ab
    where rk=1;

  updated_by_store_handwork:
    update edw.f_phy_store_order o
    set lego_store_code = s.lego_store_code 
    from edw.f_phy_store s
    where o.distributor_store_code  = s.distributor_store_code 
    and o.distributor = s.distributor 
    and lower(o.distributor) ='lewin'
    and o.lego_store_code is null or trim(o.lego_store_code) ='';
  
  update_by_phy_store:
    update edw.f_phy_store_order o
    set lego_store_code = s.lego_store_code 
    from edw.f_phy_store s
    where o.distributor_store_code  = s.distributor_store_code 
    and o.distributor = s.distributor 
    and lower(o.distributor) ='lewin'
    and (o.lego_store_code is null or trim(o.lego_store_code) ='')
    and s.lego_store_code is not null;