Staging:
  src_columns:
    distributor text,
    trans_id text,
    trans_time text,
    member_id text,
    biz_type text,
    cost_point text,
    sendout_time text

ODS:    

EDW:
  create_table_query:
    CREATE TABLE if not exists edw.f_phy_store_point_transaction (
      distributor varchar(255) not null,
      trans_id varchar(255) not null,
      trans_time timestamp not NULL,
      member_id varchar(255) not null,
      biz_type varchar(255) not null,
      cost_point decimal(15,0),
      sendout_time timestamp NULL,
      dl_batch_date varchar(8),
      dl_load_time timestamp
    )distributed by (distributor);

  insert_edw_from_ods_query:
    insert into edw.f_phy_store_point_transaction(
      distributor,
      trans_id,
      trans_time,
      member_id,
      biz_type,
      cost_point,
      sendout_time,
      dl_batch_date,
      dl_load_time
    )
    select 
      upper(distributor),
      trans_id,
      TIMESTAMP WITH TIME ZONE 'epoch' + trans_time::decimal(13) * INTERVAL '1 s',
      member_id,
      biz_type,
      cost_point::decimal(15,0),
      TIMESTAMP WITH TIME ZONE 'epoch' + sendout_time::decimal(13) * INTERVAL '1 s',
      dl_batch_date,
      dl_load_time
    from (
      select * , row_number() over( partition by upper(distributor), trans_id order by (TIMESTAMP WITH TIME ZONE 'epoch' + sendout_time::decimal(13) * INTERVAL '1 s') desc ) rk
      from ods.r_phy_store_point_transaction
    )ab
    where rk=1;
