Staging:
  src_columns:
    parent_order_id text,
    member_id text,
    payment_time text,
    distributor text,
    coupon_code text,
    coupon_name text,
    discount_type text,
    discount_value text,
    points_deduction text,
    sendout_time text    

ODS:    

EDW:
  create_table_query:
    CREATE TABLE IF NOT EXISTS edw.f_phy_store_order_coupon_dtl (
      parent_order_id varchar(255) NULL,
      member_id varchar(255) NULL,
      payment_time timestamp NULL,
      distributor varchar(255) NULL,
      coupon_code varchar(255) NULL,
      coupon_name varchar(255) NULL,
      discount_type varchar(255) NULL,
      discount_value decimal(17,2) NULL,
      points_deduction decimal(15) NULL,
      sendout_time timestamp NULL,
      dl_batch_date varchar(8),
      dl_load_time timestamp
    )distributed by (distributor,parent_order_id,coupon_code);

  insert_edw_from_ods_query:
    insert into edw.f_phy_store_order_coupon_dtl(
      parent_order_id ,
      member_id ,
      payment_time,
      distributor,
      coupon_code ,
      coupon_name ,
      discount_type,
      discount_value,
      points_deduction,
      sendout_time,
      dl_batch_date,
      dl_load_time
    )
    select 
      parent_order_id ,
      member_id ,
      TIMESTAMP WITH TIME ZONE 'epoch' + payment_time::decimal(13) * INTERVAL '1 s',
      upper(distributor),
      coupon_code ,
      coupon_name ,
      discount_type,
      discount_value::decimal(17,2),
      points_deduction::decimal(15),
      TIMESTAMP WITH TIME ZONE 'epoch' + sendout_time::decimal(13) * INTERVAL '1 s',
      dl_batch_date,
      dl_load_time
    from (
      select * , row_number() over( partition by upper(distributor), member_id, parent_order_id,coupon_code order by (TIMESTAMP WITH TIME ZONE 'epoch' + sendout_time::decimal(13) * INTERVAL '1 s') desc ) rk
      from ods.r_phy_store_order_coupon_dtl
    )ab
    where rk=1;
