Staging:
  src_columns:
    stats_time text,
    distributor text,
    lego_store_code text,
    distributor_store_code text,
    in_traffic text,
    out_traffic text,
    holdings_traffic text,
    capability text,
    sendout_time text 

ODS:    

EDW:
  create_table_query:
    CREATE TABLE if not exists edw.f_phy_store_traffic (
      stats_time timestamp NOT NULL,
      distributor varchar(255) not NULL,
      lego_store_code varchar(255) NOT NULL,
      distributor_store_code varchar(255) NOT NULL,
      in_traffic decimal(15,0),
      out_traffic decimal(15,0),
      holdings_traffic decimal(15,0),
      capability decimal(15,0),
      sendout_time timestamp NULL,
      dl_batch_date varchar(8),
      dl_load_time timestamp
    )distributed by (distributor,lego_store_code);

  insert_edw_from_ods_query:
    insert into edw.f_phy_store_traffic(
      stats_time,
      distributor,
      lego_store_code,
      distributor_store_code,
      in_traffic,
      out_traffic,
      holdings_traffic,
      capability,
      sendout_time,
      dl_batch_date,
      dl_load_time
    )
    select 
      TIMESTAMP WITH TIME ZONE 'epoch' + stats_time::decimal(13) * INTERVAL '1 s',
      upper(distributor),
      lego_store_code,
      distributor_store_code,
      in_traffic::decimal(15,0),
      case when out_traffic in ('null','') then null else out_traffic::decimal(15,0) end,
      case when holdings_traffic in ('null','') then null else holdings_traffic::decimal(15,0) end,
      case when capability in ('null','') then null else capability::decimal(15,0) end,  
      TIMESTAMP WITH TIME ZONE 'epoch' + sendout_time::decimal(13) * INTERVAL '1 s',
      dl_batch_date,
      dl_load_time
    from (
      select * , row_number() over( partition by upper(distributor), distributor_store_code, stats_time order by (TIMESTAMP WITH TIME ZONE 'epoch' + sendout_time::decimal(13) * INTERVAL '1 s') desc ) rk
      from ods.r_phy_store_traffic
    )ab
    where rk=1;

  update_by_phy_store:
    update edw.f_phy_store_traffic o
    set lego_store_code = s.lego_store_code 
    from edw.f_phy_store s
    where o.distributor_store_code  = s.distributor_store_code 
    and o.distributor = s.distributor 
    and lower(o.distributor) ='lewin'
    and (o.lego_store_code is null or trim(o.lego_store_code) ='')
    and s.lego_store_code is not null;