Staging:
  src_columns:
    platform text,
    year text,
    month text,
    primary_category  text,
    second_category  text,
    third_category text,
    piece_cnt  text,
    percent_piece_cnt  text,
    gmv_amt  text,
    percent_gmv_amt  text
    
ODS:

EDW:
  create_table_query:
    CREATE TABLE if not exists edw.f_qbt_industry_sales(
      platform varchar(255),
      year decimal(4),
      month decimal(2),
      industry varchar(255),
      primary_category varchar(255),
      second_category varchar(255),
      third_category varchar(255),
      piece_cnt  decimal(15),
      percent_piece_cnt decimal(5,4),
      gmv_amt decimal(17,2),
      percent_gmv_amt decimal(5,4),
      dl_batch_date varchar(8),
      dl_load_time timestamp
    )distributed by (platform, year, month, industry , primary_category, second_category);

  
  insert_edw_from_ods_query:
    delete from edw.f_qbt_industry_sales where industry='building toy';
    insert into edw.f_qbt_industry_sales
    (
      platform, 
      year, 
      month, 
      industry, 
      primary_category, 
      second_category, 
      third_category,
      piece_cnt, 
      percent_piece_cnt, 
      gmv_amt, 
      percent_gmv_amt, 
      dl_batch_date, 
      dl_load_time
    )
    select
      lower(platform) as platform,
      year::decimal(4,0) as year,
      month::decimal(4,0) as month,
      'building toy' as industry, 
      primary_category,
      second_category,
      third_category,
      case when piece_cnt ~ E'\\d+' then piece_cnt::decimal(15) else null end  as piece_cnt,
      case when percent_piece_cnt ~ E'^\\d+' then percent_piece_cnt::decimal(5,4) else null end  as percent_piece_cnt,
      case when gmv_amt ~ E'^\\d+' then gmv_amt::decimal(17,2) else null end  as gmv_amt,
      case when percent_gmv_amt ~ E'^\\d+' then percent_gmv_amt::decimal(5,4) else null end  as percent_gmv_amt,
      dl_batch_date,
      now()
    from ods.r_qbt_building_toy_industry_sales
    
