Staging:
  src_columns:
    platform text,
    year text,
    month text,
    shop text,
    shopkeeper_name text,
    gmv_amt text,
    piece_cnt text
ODS:

EDW:
  create_table_query:
    CREATE TABLE if not exists edw.f_qbt_store_sales(
      platform varchar(255),
      year decimal(4),
      month decimal(2),
      shop varchar(255),
      shopkeeper_name varchar(255),
      gmv_amt decimal(17,2),
      piece_cnt decimal(15),
      dl_batch_date varchar(8),
      dl_load_time timestamp,
      constraint pk_store_sales_id primary key(platform, year, month, shop, shopkeeper_name )
    )distributed by (platform, year, month, shop, shopkeeper_name);

  
  insert_edw_from_ods_query:
    delete from edw.f_qbt_store_sales;
    insert into edw.f_qbt_store_sales
    (
      platform, 
      year, 
      month, 
      shop, 
      shopkeeper_name, 
      gmv_amt, 
      piece_cnt, 
      dl_batch_date, 
      dl_load_time
    )
    select
      lower(platform) as platform,
      year::decimal(4,0) as year,
      month::decimal(4,0) as month,
      shop,
      shopkeeper_name,
      case when gmv_amt ~ E'\\d+' then replace(trim(gmv_amt),',','')::decimal(17,2) else null end as gmv_amt,
      case when piece_cnt ~ E'\\d+' then replace(trim(piece_cnt),',','')::decimal(15) else null end as piece_cnt,
      dl_batch_date,
      now()
    from ods.r_qbt_store_sales
    
