Staging:
  src_columns:
    year text,
    month text,
    week text,
    start_time text,
    end_time text,
    brand text,
    lego_sku_id text,
    sku_cn_name text,
    platform text,
    shop text,
    gmv_amt text,
    piece_cnt text

ODS:

EDW:
  create_table_query:
    CREATE TABLE if not exists edw.f_qbt_sku_monitor(
      year decimal(4),
      month decimal(2),
      week decimal(2),
      start_time date,
      end_time date,
      brand varchar(255),
      lego_sku_id varchar(255),
      sku_cn_name varchar(255),
      platform varchar(255),
      shop varchar(255),
      gmv_amt decimal(17,2),
      piece_cnt decimal(15),
      current_row varchar(255),
      store_type varchar(255),
      rsp numeric(17,6),
      dl_batch_date varchar(8),
      dl_load_time timestamp
    )distributed by (year, month, week, start_time, end_time,brand,lego_sku_id,sku_cn_name,platform,shop );

  
  scd3_update_query:
    create temporary table t1 as 
    select 
      year::decimal(4),
      month::decimal(2),
      week::decimal(2),
      case when(start_time ~ E'^\\d+-\\d+-\\d+ \\d+:\\d+:\\d+') then to_date(start_time, 'yyyy-mm-dd') else null end as start_time,
      case when(end_time ~ E'^\\d+-\\d+-\\d+ \\d+:\\d+:\\d+') then to_date(end_time, 'yyyy-mm-dd') else null end as end_time,
      brand,
      lego_sku_id,
      sku_cn_name,
      lower(a.platform) as platform,
      a.shop,
      sum(case when gmv_amt ~ E'\\d+' then replace(trim(gmv_amt),',','')::decimal(17,2) else null end) as gmv_amt,
      sum(case when piece_cnt ~ E'\\d+' then replace(trim(piece_cnt),',','')::decimal(15) else null end) as piece_cnt,
      'Y' as current_row,
      max(case when lower(a.platform) ='tb' then '淘宝' 
           when lower(a.platform) ='tmall' and b.platform is not null then b.store_type
           when lower(a.platform) ='tmall' and b.platform is null then '天猫B店' 
           else null 
        end) as store_type,
      dl_batch_date,
      now()
    from ods.r_qbt_sku_monitor a
      left join edw.d_qbt_competitor_store_mapping b on lower(a.platform) = lower(b.platform) and lower(a.shop) = lower(b.shop)
    where dl_batch_date = '{batch_date}'
    group by year, month, week, start_time, end_time,brand,lego_sku_id,sku_cn_name, a.platform,a.shop,dl_batch_date;

    update edw.f_qbt_sku_monitor a
      set current_row = 'N'
    from t1 b
    where 
      a.year = b.year
      and a.shop = b.shop
      and a.month = b.month
      and a.week = b.week
      and a.start_time =  b.start_time
      and a.end_time = b.end_time
      and a.brand = b.brand
      and a.lego_sku_id = b.lego_sku_id
      and a.sku_cn_name = b.sku_cn_name
      and a.platform = b.platform;

    INSERT INTO edw.f_qbt_sku_monitor(
      year, 
      month, 
      week, 
      start_time, 
      end_time, 
      brand, 
      lego_sku_id, 
      sku_cn_name, 
      platform, 
      shop,  
      gmv_amt, 
      piece_cnt,
      current_row,
      store_type,
      dl_batch_date,
      dl_load_time
    ) 
    select * from t1;

    
    update edw.f_qbt_sku_monitor a
    set  rsp = p1.rsp
    from (
          select * from(
            select 
              row_number() over(partition by m.year, m.month, m.week, m.start_time,m.brand, m.lego_sku_id, m.platform, m.shop order by case when year >= p.year_version::int then year - p.year_version::int else (year - p.year_version::int)*-1 + 100 end) as rsp_gap,
              m.year,
              m.month, 
              m.week,
              m.start_time,
              m.end_time,
              m.brand,
              m.lego_sku_id,
              m.platform,
              m.shop,
              p.rsp
          from edw.f_qbt_sku_monitor m 
              left join edw.d_dl_product_info p on m.lego_sku_id =p.lego_sku_id
          ) t1 where rsp_gap=1
        )p1 
    where a.year = p1.year
        and a.month = p1.month
        and a.start_time = p1.start_time
        and a.end_time = p1.end_time
        and a.brand = p1.brand
        and a.lego_sku_id = p1.lego_sku_id
        and lower(a.platform) = lower(p1.platform)
        and lower(a.shop) = lower(p1.shop)
        and a.dl_batch_date = '{batch_date}'
        

  # updated_by_sku_monitor:
  #   delete from dm.a_dl_qbt_sku_monitor;

  #   insert into dm.a_dl_qbt_sku_monitor
  #   select 
  #     year, 
  #     month, 
  #     week, 
  #     start_time, 
  #     end_time,
  #     brand,
  #     lego_sku_id,
  #     sku_cn_name,
  #     platform,
  #     shop,
  #     sum(gmv_amt) as gmv_amt,
  #     sum(piece_cnt) as piece_cnt,
  #     now()
  #   from edw.f_qbt_sku_monitor 
  #   where current_row='Y'
  #   group by year, month, week, start_time, end_time,brand,lego_sku_id,sku_cn_name,platform,shop;
