name: Legacy data migration CD

on:
  push:
    branches:
      - dev-legacy
jobs:
  legacy-deploy-dev:
    runs-on: [self-hosted, linux, dev]
    steps:
    - uses: actions/checkout@v1
    - name: copy source code to target
      run: |
        cp -rf ./dags/lego/legacy/  /cdp/airflow/dags/lego/
        cp -rf ./dags/lego/lego/dl_calendar_dag.py  /cdp/airflow/dags/lego/lego/
        cp -rf ./dags/lego/tasks/sqls/lgc_* /cdp/airflow/dags/lego/tasks/sqls/
        cp -rf ./dags/lego/tasks/sqls/dl_calendar.yml /cdp/airflow/dags/lego/tasks/sqls/
        cp -rf ./dags/lego/tasks/sqls/dl_product_info_v2.yml /cdp/airflow/dags/lego/tasks/sqls/
        cp -rf ./dags/lego/tasks/sqls/dl_phy_store.yml /cdp/airflow/dags/lego/tasks/sqls/
        cp -rf ./dags/lego/tasks/config/entity_conf.yml  /cdp/airflow/dags/lego/tasks/config/
        cp -rf ./dags/lego/lego/dl_product_info_v2_dag.py  /cdp/airflow/dags/lego/lego/
        cp -rf ./dags/lego/lego/dl_phy_store_dag.py  /cdp/airflow/dags/lego/lego/
        cp -rf ./dags/lego/lego/dl_product_info_v2_daily_update_dag.py  /cdp/airflow/dags/lego/lego/