# create dev branch CD 
name: dev CD
on:
  push:
    branches:
      - dev
jobs:
  dev-deploy:
    runs-on: [self-hosted, linux]
    steps:
    - uses: actions/checkout@v1
    - name: copy source code to target
      run: |
        cp -rf ./dags/lego/tasks/utils/ /cdp/airflow/dags/lego/tasks/utils/
        cp -rf ./dags/lego/tasks/src2stg.py  /cdp/airflow/dags/lego/tasks/
        cp -rf ./dags/lego/tasks/sqls/dl_tm_shopper.yml  /cdp/airflow/dags/lego/tasks/sqls/