# create dev branch CD 
name: dev-shopper CD
on:
  push:
    branches:
      - dev-shopper
jobs:
  shopper-deploy:
    runs-on: [self-hosted, linux]
    steps:
    - uses: actions/checkout@v1
    - name: copy source code to target
      run: |
        [[ ! -d "/cdp/airflow/dags/lego/analysis" ]]&& mkdir "/cdp/airflow/dags/lego/analysis"
        cp -rf ./dags/lego/lego/bu_tm_gwp_dag.py /cdp/airflow/dags/lego/lego/
        cp -rf ./dags/lego/lego/bu_tm_sku_map_dag.py  /cdp/airflow/dags/lego/lego/
        cp -rf ./dags/lego/lego/dl_product_info_dag.py  /cdp/airflow/dags/lego/lego/
        cp -rf ./dags/lego/oms/oms_order_dag.py  /cdp/airflow/dags/lego/oms/
        cp -rf ./dags/lego/oms/oms_order_dtl_dag.py  /cdp/airflow/dags/lego/oms/
        cp -rf ./dags/lego/tasks/config/entity_conf.yml  /cdp/airflow/dags/lego/tasks/sqls/
        cp -rf ./dags/lego/tasks/sqls/dl_tm_shopper.yml  /cdp/airflow/dags/lego/tasks/sqls/
        cp -rf ./dags/lego/tasks/sqls/qbt_sku_monitor.yml   /cdp/airflow/dags/lego/tasks/sqls/
        cp -rf ./dags/lego/tasks/sqls/qbt_store_sales.yml   /cdp/airflow/dags/lego/tasks/sqls/
        cp -rf ./dags/lego/analysis/*   /cdp/airflow/dags/lego/analysis/